// @ts-ignore -- generated by wasm-pack before package build
import * as wasmModule from '../wasm/pptx/ooxml_markdown_pptx.js';

type MarkdownWasmModule = {
  initSync: (init: { module: WebAssembly.Module }) => unknown;
  to_markdown: (bytes: Uint8Array) => string;
};

const wasm = wasmModule as MarkdownWasmModule;
let initialized = false;

function toUint8(buffer: ArrayBuffer | Uint8Array): Uint8Array {
  if (ArrayBuffer.isView(buffer)) {
    return new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength);
  }
  return new Uint8Array(buffer);
}

/** Initialise the PPTX Markdown projector from its dedicated WASM bytes. */
export function initFromBytes(bytes: ArrayBuffer | Uint8Array): void {
  if (initialized) return;
  const module = new WebAssembly.Module(toUint8(bytes) as unknown as ArrayBuffer);
  wasm.initSync({ module });
  initialized = true;
}

/** Convert a PPTX archive to GitHub-flavoured Markdown. */
export function toMarkdown(bytes: ArrayBuffer | Uint8Array): string {
  if (!initialized) {
    throw new Error('markdown wasm not initialized — call initFromBytes() first');
  }
  return wasm.to_markdown(toUint8(bytes));
}
