// Generated by scripts/check-public-api.mjs.
// This file records every local declaration reachable from the PPTX public entry.
// Do not edit by hand.

// --- file: pptx.d.ts ---
export interface ArrowEnd {
    type: string;
    w: string;
    len: string;
}
export function autoResize(render: (width: number, height: number) => void | Promise<void>, element: Element, opts?: AutoResizeOptions): () => void;
export interface AutoResizeOptions {
    pauseWhenHidden?: boolean;
}
export interface Bevel3d {
    w: number;
    h: number;
    prst: string;
}
export interface BlipBullet {
    type: 'blip';
    imagePath: string;
    mimeType: string;
    sizePct: number | null;
    sizePts?: number;
}
export function buildPptxHighlightLayer(layer: HTMLDivElement, runs: PptxTextRunInfo[], matches: PptxHighlightMatch[], cssWidth: number, cssHeight: number, measureForFont: (font: string) => (s: string) => number, colors?: PptxHighlightColors): void;
export function buildPptxTextLayer(layer: HTMLDivElement, runs: PptxTextRunInfo[], cssWidth: number, cssHeight: number, onHyperlinkClick?: (target: HyperlinkTarget) => void, slideIndex?: number): void;
export type Bullet = Bullet__emitterCollision1 | BlipBullet;
type Bullet__emitterCollision1 = {
    type: 'none';
} | {
    type: 'inherit';
} | {
    type: 'char';
    char: string;
    color: string | null;
    sizePct: number | null;
    sizePts?: number;
    fontFamily: string | null;
} | {
    type: 'autoNum';
    numType: string;
    startAt: number | null;
    color: string | null;
    sizePct?: number | null;
    sizePts?: number;
    fontFamily?: string | null;
};
export interface Camera3d {
    prst: string;
    fov?: number;
    zoom?: number;
    rot?: Rot3d;
}
export interface ChartAreaGroupDecorations {
    groupIndex: number;
    dropLines?: ChartDecorationLineStyle | null;
}
export interface ChartBarGroupDecorations {
    groupIndex: number;
    seriesLines?: ChartDecorationLineStyle[] | null;
}
export interface ChartDataLabelOverride {
    idx: number;
    text: string;
    richRuns?: ChartTextRun[];
    position?: string;
    fontColor?: string;
    fontPaintAuthored?: boolean;
    fontHidden?: boolean;
    fontSizeHpt?: number;
    fontFace?: string;
    fontBold?: boolean;
    fontItalic?: boolean;
    fontLanguage?: string;
    fontBaseline?: number;
    textRotation?: number;
    textWrap?: string;
    textVerticalAnchor?: string;
    textVerticalMode?: string;
    textLInsEmu?: number;
    textTInsEmu?: number;
    textRInsEmu?: number;
    textBInsEmu?: number;
    textBodyAuthored?: boolean;
    textAlign?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string;
    formatCode?: string;
    separator?: string;
    manualLayout?: ChartManualLayout;
    labelBox?: ChartLabelBox;
    showVal?: boolean;
    showCatName?: boolean;
    showSerName?: boolean;
    showPercent?: boolean;
    showBubbleSize?: boolean;
    showLegendKey?: boolean;
    deleted?: boolean;
}
export interface ChartDataPointOverride {
    idx: number;
    color?: string;
    fillHidden?: boolean;
    chartexStyle?: ChartExElementStyle | null;
    lineColor?: string;
    lineWidthEmu?: number;
    lineDash?: string;
    lineHidden?: boolean;
    markerSymbol?: string;
    markerSize?: number;
    markerFill?: string;
    markerFillPaint?: Fill | null;
    markerFillPaintAuthored?: boolean | null;
    markerLine?: string;
    markerLineWidthEmu?: number;
    bubble3D?: boolean | null;
    explosion?: number;
}
export interface ChartDataTable {
    showHorizontalBorder: boolean;
    showVerticalBorder: boolean;
    showOutline: boolean;
    showKeys: boolean;
    fontSizeHpt?: number | null;
    fontFace?: string | null;
    fontColor?: string | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    fillColor?: string | null;
    fill?: SolidFill | GradientFill | PatternFill | null;
    fillHidden?: boolean | null;
    fillPaintAuthored?: boolean | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden?: boolean | null;
}
export interface ChartDecorationLineStyle {
    color?: string | null;
    paintAuthored?: boolean | null;
    widthEmu?: number | null;
    dash?: string | null;
    cap?: string | null;
    join?: string | null;
    hidden?: boolean | null;
}
export interface ChartDisplayUnits {
    divisor: number;
    builtInUnit?: string | null;
    label?: ChartDisplayUnitsLabel | null;
}
export interface ChartDisplayUnitsLabel {
    text?: string | null;
    manualLayout?: ChartManualLayout | null;
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    fontColor?: string | null;
    fontFace?: string | null;
    rotation?: number | null;
    boxStyle?: ChartLabelBox | null;
}
export interface ChartElement {
    type: 'chart';
    id?: string;
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    chart: ChartModel;
}
export interface ChartErrBars {
    dir: string;
    barType: string;
    plus: (number | null)[];
    minus: (number | null)[];
    noEndCap: boolean;
    color?: string;
    lineWidthEmu?: number;
    dash?: string;
    hidden?: boolean;
}
export interface ChartexBoxSeries {
    name: string;
    chartexFormatIdx?: number | null;
    color?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    chartexStyle?: ChartExElementStyle | null;
    valuesByCategory: number[][];
    meanMarker: boolean;
    meanLine: boolean;
    showOutliers: boolean;
    showNonoutliers: boolean;
    quartileMethod: string;
}
export interface ChartexBoxWhisker {
    oneBoxPerSeries?: boolean;
    categories: string[];
    series: ChartexBoxSeries[];
}
export interface ChartExElementStyle {
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    fontColor?: string | null;
    fontPaintAuthored?: boolean | null;
    fontHidden?: boolean | null;
    fontFace?: string | null;
    fontLanguage?: string | null;
    fontBaseline?: number | null;
    textRotation?: number | null;
    textWrap?: string | null;
    textVerticalAnchor?: string | null;
    textVerticalMode?: string | null;
    textLInsEmu?: number | null;
    textTInsEmu?: number | null;
    textRInsEmu?: number | null;
    textBInsEmu?: number | null;
    textBodyAuthored?: boolean | null;
    fillPaints?: Array<Fill | null> | null;
    fillColors?: Array<string | null> | null;
    fillHidden?: boolean | null;
    fillPaintAuthored?: boolean | null;
    fillNoStyle?: boolean | null;
    lineColors?: Array<string | null> | null;
    linePaints?: Array<SolidFill | GradientFill | PatternFill | null> | null;
    linePaintAuthored?: boolean | null;
    lineWidthEmu?: number | null;
    lineHidden?: boolean | null;
    lineNoStyle?: boolean | null;
    lineDash?: string | null;
    lineDashAuthored?: boolean | null;
    lineCustomDash?: ChartLineDashSegment[] | null;
    lineCap?: string | null;
    lineJoin?: string | null;
    lineCompound?: string | null;
    fillColorIndex?: number | null;
    lineColorIndex?: number | null;
}
export interface ChartexGeography {
    projectionType?: 'mercator' | 'miller' | 'robinson' | 'albers' | string | null;
    viewedRegionType?: string | null;
    cultureLanguage?: string | null;
    cultureRegion?: string | null;
    attribution?: string | null;
    cacheProvider?: string | null;
    cachePresent: boolean;
}
export interface ChartexHistogramBinning {
    binSize?: number | null;
    binCount?: number | null;
    intervalClosed?: 'l' | 'r' | null;
    underflow?: number | null;
    overflow?: number | null;
}
export interface ChartexRegionMap {
    rows: ChartexRegionMapRow[];
    regionLabelLayout?: 'none' | 'bestFitOnly' | 'showAll' | null;
    geography?: ChartexGeography | null;
    colors?: ChartexRegionMapColors | null;
}
export interface ChartexRegionMapColors {
    stopCount?: 2 | 3 | null;
    minColor?: string | null;
    midColor?: string | null;
    maxColor?: string | null;
    minPosition?: ChartexValueColorStop | null;
    midPosition?: ChartexValueColorStop | null;
    maxPosition?: ChartexValueColorStop | null;
}
export interface ChartexRegionMapRow {
    label: string;
    entityId?: string | null;
    value?: number | null;
}
export interface ChartExRenderer {
    render(ctx: CanvasRenderingContext2D, chart: ChartModel, rect: ChartRect, ptToPx: number, shapeRotationDeg?: number): boolean;
}
export interface ChartexSunburst {
    rows: ChartexSunburstRow[];
}
export interface ChartexSunburstRow {
    path: string[];
    size: number;
}
export interface ChartexTreemap {
    rows: ChartexSunburstRow[];
    parentLabelLayout?: string | null;
}
export interface ChartexValueColorStop {
    kind: 'extremeValue' | 'number' | 'percent' | string;
    value?: number | null;
}
export interface ChartLabelBox {
    fill?: string;
    fillPaint?: SolidFill | GradientFill | PatternFill | null;
    fillHidden?: boolean | null;
    fillPaintAuthored?: boolean | null;
    borderColor?: string;
    borderFill?: SolidFill | GradientFill | PatternFill | null;
    borderWidthEmu?: number;
    borderHidden?: boolean | null;
    borderPaintAuthored?: boolean | null;
    borderDash?: string | null;
    borderDashAuthored?: boolean | null;
    borderCustomDash?: ChartLineDashSegment[] | null;
    borderCap?: string | null;
    borderJoin?: string | null;
    borderCompound?: string | null;
}
export interface ChartLegendEntryOverride {
    idx: number;
    deleted?: boolean | null;
    fontFace?: string | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
}
export type ChartLineDashSegment = DrawingMLCustomDashSegment;
export interface ChartLineGroupDecorations {
    groupIndex: number;
    dropLines?: ChartDecorationLineStyle | null;
    hiLowLines?: ChartDecorationLineStyle | null;
    upDownBars?: ChartStockUpDownBarStyle | null;
}
export interface ChartManualLayout {
    xMode?: string;
    yMode?: string;
    wMode?: string;
    hMode?: string;
    layoutTarget?: string;
    x: number;
    y: number;
    w?: number;
    h?: number;
}
export interface ChartModel {
    chartType: ChartType;
    title: string | null;
    titleRichRuns?: ChartTextRun[] | null;
    titlePresent?: boolean;
    categories: string[];
    categorySourceHidden?: boolean[] | null;
    categoryLevels?: string[][] | null;
    series: ChartSeries[];
    plotGroups?: ChartPlotGroup[] | null;
    chartTextBoxes?: ChartTextBox[] | null;
    varyColors?: boolean | null;
    showDataLabels: boolean;
    valMin: number | null;
    valMax: number | null;
    catAxisTitle: string | null;
    valAxisTitle: string | null;
    catAxisHidden: boolean;
    valAxisHidden: boolean;
    catAxisLineHidden: boolean;
    valAxisLineHidden: boolean;
    plotAreaBg: string | null;
    plotAreaFill?: Fill | null;
    plotAreaFillHidden?: boolean | null;
    plotAreaFillPaintAuthored?: boolean | null;
    plotAreaFillAutomatic?: boolean | null;
    plotAreaLineColor?: string | null;
    plotAreaLineFill?: SolidFill | GradientFill | PatternFill | null;
    plotAreaLineWidthEmu?: number | null;
    plotAreaLineDash?: string | null;
    plotAreaLineDashAuthored?: boolean | null;
    plotAreaLineCustomDash?: ChartLineDashSegment[] | null;
    plotAreaLineCap?: string | null;
    plotAreaLineJoin?: string | null;
    plotAreaLineCompound?: string | null;
    plotAreaLineHidden?: boolean | null;
    plotAreaLinePaintAuthored?: boolean | null;
    chartBg: string | null;
    chartFill?: Fill | null;
    chartFillHidden?: boolean | null;
    chartFillPaintAuthored?: boolean | null;
    roundedCorners?: boolean | null;
    plotVisibleOnly?: boolean | null;
    showLegend: boolean;
    dataTable?: ChartDataTable | null;
    legendPos: 'r' | 'l' | 't' | 'b' | 'tr' | null;
    legendOverlay?: boolean | null;
    legendEntries?: ChartLegendEntryOverride[] | null;
    catAxisCrossBetween: 'between' | 'midCat' | string;
    valAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    catAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    valAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    catAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    titleFontSizeHpt: number | null;
    titleFontColor: string | null;
    titleFontFace: string | null;
    catAxisFontSizeHpt: number | null;
    valAxisFontSizeHpt: number | null;
    catAxisFontColor?: string | null;
    valAxisFontColor?: string | null;
    dataLabelFontSizeHpt: number | null;
    dataLabelFontBold?: boolean | null;
    subtotalIndices: number[];
    legendManualLayout?: LegendManualLayout | null;
    valAxisFormatCode?: string | null;
    valAxisDisplayUnits?: ChartDisplayUnits | null;
    catAxisDisplayUnits?: ChartDisplayUnits | null;
    barGapWidth?: number | null;
    barOverlap?: number | null;
    dataLabelPosition?: string | null;
    dataLabelFontColor?: string | null;
    dataLabelFormatCode?: string | null;
    titleFontBold?: boolean | null;
    catAxisFontBold?: boolean | null;
    catAxisFontItalic?: boolean | null;
    valAxisFontBold?: boolean | null;
    valAxisFontItalic?: boolean | null;
    catAxisTitleFontSizeHpt?: number | null;
    catAxisTitleFontBold?: boolean | null;
    catAxisTitleFontItalic?: boolean | null;
    catAxisTitleFontColor?: string | null;
    catAxisTitleRotation?: number | null;
    catAxisTitleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    catAxisTitleManualLayout?: ChartManualLayout | null;
    catAxisTitleTextVerticalInsetEmu?: number | null;
    valAxisTitleFontSizeHpt?: number | null;
    valAxisTitleFontBold?: boolean | null;
    valAxisTitleFontItalic?: boolean | null;
    valAxisTitleFontColor?: string | null;
    valAxisTitleRotation?: number | null;
    valAxisTitleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    valAxisTitleManualLayout?: ChartManualLayout | null;
    valAxisTitleTextVerticalInsetEmu?: number | null;
    catAxisFontFace?: string | null;
    valAxisFontFace?: string | null;
    catAxisTitleFontFace?: string | null;
    valAxisTitleFontFace?: string | null;
    dataLabelFontFace?: string | null;
    legendFontFace?: string | null;
    legendFontColor?: string | null;
    legendFontSizeHpt?: number | null;
    legendFontBold?: boolean | null;
    legendFillColor?: string | null;
    legendFill?: Fill | null;
    legendFillHidden?: boolean | null;
    legendFillPaintAuthored?: boolean | null;
    legendLineColor?: string | null;
    legendLineFill?: SolidFill | GradientFill | PatternFill | null;
    legendLineWidthEmu?: number | null;
    legendLineDash?: string | null;
    legendLineDashAuthored?: boolean | null;
    legendLineCustomDash?: ChartLineDashSegment[] | null;
    legendLineCap?: string | null;
    legendLineJoin?: string | null;
    legendLineCompound?: string | null;
    legendLineHidden?: boolean | null;
    legendLinePaintAuthored?: boolean | null;
    themeMajorFontLatin?: string | null;
    themeMinorFontLatin?: string | null;
    chartBorderColor?: string | null;
    chartBorderLineFill?: SolidFill | GradientFill | PatternFill | null;
    chartBorderWidthEmu?: number | null;
    chartBorderDash?: string | null;
    chartBorderDashAuthored?: boolean | null;
    chartBorderCustomDash?: ChartLineDashSegment[] | null;
    chartBorderCap?: string | null;
    chartBorderJoin?: string | null;
    chartBorderCompound?: string | null;
    chartBorderHidden?: boolean | null;
    chartBorderPaintAuthored?: boolean | null;
    catAxisCrosses?: string | null;
    catAxisCrossesAt?: number | null;
    valAxisCrosses?: string | null;
    valAxisCrossesAt?: number | null;
    catAxisLineColor?: string | null;
    catAxisLineWidthEmu?: number | null;
    catAxisLineDash?: string | null;
    catAxisLinePaintAuthored?: boolean | null;
    valAxisLineColor?: string | null;
    valAxisLineWidthEmu?: number | null;
    valAxisLineDash?: string | null;
    valAxisLinePaintAuthored?: boolean | null;
    catAxisFormatCode?: string | null;
    catAxisMin?: number | null;
    catAxisMax?: number | null;
    titleManualLayout?: ChartManualLayout | null;
    plotAreaManualLayout?: ChartManualLayout | null;
    scatterStyle?: string | null;
    bubbleScale?: number | null;
    bubbleSizeRepresents?: 'area' | 'w' | null;
    showNegativeBubbles?: boolean | null;
    radarStyle?: string | null;
    secondaryValAxis?: SecondaryValueAxis | null;
    secondaryCatAxis?: SecondaryValueAxis | null;
    date1904?: boolean;
    holeSize?: number | null;
    firstSliceAngle?: number | null;
    dispBlanksAs?: string | null;
    showDataLabelsOverMax?: boolean | null;
    valAxisMajorGridlines?: boolean | null;
    catAxisMajorGridlines?: boolean | null;
    valAxisGridlineColor?: string | null;
    valAxisGridlineWidthEmu?: number | null;
    valAxisGridlineDash?: string | null;
    catAxisGridlineColor?: string | null;
    catAxisGridlineWidthEmu?: number | null;
    catAxisGridlineDash?: string | null;
    valAxisMinorGridlines?: boolean | null;
    valAxisMinorGridlineColor?: string | null;
    valAxisMinorGridlineWidthEmu?: number | null;
    valAxisMinorGridlineDash?: string | null;
    catAxisMinorGridlines?: boolean | null;
    catAxisMinorGridlineColor?: string | null;
    catAxisMinorGridlineWidthEmu?: number | null;
    catAxisMinorGridlineDash?: string | null;
    valAxisMajorUnit?: number | null;
    valAxisMinorUnit?: number | null;
    catAxisMajorUnit?: number | null;
    catAxisMinorUnit?: number | null;
    catAxisIsDate?: boolean | null;
    catAxisBaseTimeUnit?: 'days' | 'months' | 'years' | string | null;
    catAxisMajorTimeUnit?: 'days' | 'months' | 'years' | string | null;
    catAxisMinorTimeUnit?: 'days' | 'months' | 'years' | string | null;
    catAxisNoMultiLevelLabels?: boolean | null;
    valAxisLogBase?: number | null;
    catAxisLogBase?: number | null;
    valAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisTickLabelPos?: string | null;
    catAxisTickLabelSkip?: number | null;
    catAxisTickMarkSkip?: number | null;
    catAxisLabelAlignment?: 'l' | 'ctr' | 'r' | string | null;
    catAxisLabelOffsetPercent?: number | null;
    valAxisTickLabelPos?: string | null;
    catAxisLabelRotation?: number | null;
    lineGroupDecorations?: ChartLineGroupDecorations[] | null;
    areaGroupDecorations?: ChartAreaGroupDecorations[] | null;
    barGroupDecorations?: ChartBarGroupDecorations[] | null;
    stockDropLines?: ChartDecorationLineStyle | null;
    stockHiLowLineStyle?: ChartDecorationLineStyle | null;
    stockHiLowLines?: boolean | null;
    stockHiLowLineColor?: string | null;
    stockUpDownBars?: boolean | null;
    stockUpDownBarStyle?: ChartStockUpDownBarStyle | null;
    stockAutomaticStyle?: {
        lineColor: string;
        lineWidthEmu: number;
        upFillColor: string;
        downFillColor: string;
    } | null;
    surfaceWireframe?: boolean | null;
    surfaceBandFormats?: ChartSurfaceBandFormat[] | null;
    legacyChartStyle?: number | null;
    themeAccentColors?: string[] | null;
    ofPie?: ChartOfPie | null;
    threeD?: ChartThreeD | null;
    chartexBox?: ChartexBoxWhisker | null;
    chartexSunburst?: ChartexSunburst | null;
    chartexTreemap?: ChartexTreemap | null;
    chartexRegionMap?: ChartexRegionMap | null;
    chartexHistogramBinning?: ChartexHistogramBinning | null;
    chartexAccents?: string[] | null;
    chartexColorPalette?: Array<string | null> | null;
    chartexColorStyleMethod?: string | null;
    chartStyleRoles?: Partial<Record<ChartStyleRole, ChartExElementStyle>> | null;
    chartStyleColorPalette?: Array<string | null> | null;
    chartStyleColorMethod?: string | null;
    chartStyleMarkerSizePt?: number | null;
    chartStyleMarkerSymbol?: string | null;
    chartexDataPointStyle?: ChartExElementStyle | null;
    chartexDataPointLineStyle?: ChartExElementStyle | null;
    chartexSeriesLineStyle?: ChartExElementStyle | null;
    chartexDataPointMarkerStyle?: ChartExElementStyle | null;
    chartexMarkerSizePt?: number | null;
    chartexMarkerSymbol?: string | null;
    chartexConnectorLines?: boolean | null;
}
export interface ChartOfPie {
    type: 'pie' | 'bar';
    splitType: 'auto' | 'cust' | 'percent' | 'pos' | 'val';
    splitTypeAuthored?: boolean | null;
    splitPos?: number | null;
    splitPosAuthored?: boolean | null;
    customSplitIndices?: number[] | null;
    secondPieSizePercent: number;
    gapWidthPercent: number;
    seriesLines: boolean;
}
export interface ChartPlotGroup {
    kind: ChartPlotGroupKind;
    seriesStart: number;
    seriesCount: number;
    categoryAxis: ChartPlotGroupAxisSlot;
    valueAxis: ChartPlotGroupAxisSlot;
    seriesAxis: ChartPlotGroupAxisSlot;
    axisIds?: string[] | null;
    grouping?: string | null;
    barDirection?: string | null;
    scatterStyle?: string | null;
    radarStyle?: string | null;
    gapWidth?: number | null;
    overlap?: number | null;
    bubbleScale?: number | null;
    bubbleSizeRepresents?: 'area' | 'w' | null;
    showNegativeBubbles?: boolean | null;
}
export type ChartPlotGroupAxisSlot = 'primary' | 'secondary' | 'none' | 'unresolved';
export type ChartPlotGroupKind = 'area' | 'area3D' | 'line' | 'line3D' | 'stock' | 'radar' | 'scatter' | 'pie' | 'pie3D' | 'doughnut' | 'bar' | 'bar3D' | 'ofPie' | 'surface' | 'surface3D' | 'bubble';
export interface ChartRect {
    x: number;
    y: number;
    w: number;
    h: number;
}
export interface ChartRegionMapRenderer {
    render(ctx: CanvasRenderingContext2D, chart: ChartModel, rect: ChartRect, ptToPx: number, shapeRotationDeg?: number): boolean;
}
export interface ChartSeries {
    name: string;
    chartexFormatIdx?: number | null;
    color: string | null;
    fillPattern?: PatternFill | null;
    invertIfNegative?: boolean | null;
    automaticNegativeStyle?: boolean | null;
    invertedFill?: SolidFill | GradientFill | PatternFill | null;
    invertedFillHidden?: boolean | null;
    invertedFillAuthored?: boolean | null;
    invertedLineColor?: string | null;
    invertedLineWidthEmu?: number | null;
    invertedLineHidden?: boolean | null;
    invertedLineAuthored?: boolean | null;
    chartexStyle?: ChartExElementStyle | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    threeDShape?: 'box' | 'cylinder' | 'cone' | 'coneToMax' | 'pyramid' | 'pyramidToMax' | string | null;
    values: (number | null)[];
    sourceHidden?: boolean[] | null;
    dataPointColors?: (string | null)[] | null;
    explosion?: number | null;
    dataLabelColors?: (string | null)[] | null;
    labelColor?: string | null;
    seriesType?: string | null;
    lineGroupIndex?: number | null;
    areaGroupIndex?: number | null;
    barGroupIndex?: number | null;
    barGroupDirection?: 'bar' | 'col' | string | null;
    barGroupGrouping?: 'standard' | 'clustered' | 'stacked' | 'percentStacked' | string | null;
    barGroupGapWidth?: number | null;
    barGroupOverlap?: number | null;
    useSecondaryAxis?: boolean | null;
    categories?: string[] | null;
    bubbleXSourceIsString?: boolean | null;
    showMarker?: boolean | null;
    valFormatCode?: string | null;
    catFormatCode?: string | null;
    catFormatBuiltinId?: number | null;
    catFormatCodes?: (string | null)[] | null;
    markerSymbol?: string | null;
    automaticMarkerSymbol?: string | null;
    markerSize?: number | null;
    markerFill?: string | null;
    markerFillPaint?: Fill | null;
    markerFillPaintAuthored?: boolean | null;
    markerLine?: string | null;
    markerLineWidthEmu?: number | null;
    dataPointOverrides?: ChartDataPointOverride[] | null;
    dataLabelOverrides?: ChartDataLabelOverride[] | null;
    seriesDataLabels?: ChartSeriesDataLabels | null;
    errBars?: ChartErrBars[] | null;
    bubbleSizes?: (number | null)[] | null;
    bubble3DGroupDefault?: boolean | null;
    bubble3D?: boolean | null;
    smooth?: boolean | null;
    trendLines?: ChartTrendline[] | null;
    lineHidden?: boolean | null;
}
export interface ChartSeriesDataLabels {
    deleted?: boolean | null;
    showVal: boolean;
    showCatName: boolean;
    showSerName: boolean;
    showPercent: boolean;
    showBubbleSize?: boolean;
    showLegendKey?: boolean;
    position?: string;
    fontColor?: string;
    fontPaintAuthored?: boolean;
    fontHidden?: boolean;
    formatCode?: string;
    separator?: string;
    fontBold?: boolean;
    fontItalic?: boolean;
    fontLanguage?: string;
    fontBaseline?: number;
    fontSizeHpt?: number;
    fontFace?: string;
    textRotation?: number;
    textWrap?: string;
    textVerticalAnchor?: string;
    textVerticalMode?: string;
    textLInsEmu?: number;
    textTInsEmu?: number;
    textRInsEmu?: number;
    textBInsEmu?: number;
    textBodyAuthored?: boolean;
    textAlign?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string;
    labelBox?: ChartLabelBox;
    showLeaderLines?: boolean;
    leaderLineColor?: string;
    leaderLineWidthEmu?: number;
    leaderLineHidden?: boolean;
    leaderLineDash?: string;
}
export interface ChartStockBarPaint {
    fillColor?: string | null;
    fill?: SolidFill | GradientFill | PatternFill | null;
    fillPaintAuthored?: boolean | null;
    fillHidden?: boolean | null;
    lineColor?: string | null;
    linePaintAuthored?: boolean | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineCap?: string | null;
    lineJoin?: string | null;
    lineHidden?: boolean | null;
}
export interface ChartStockUpDownBarStyle {
    gapWidthPercent: number;
    up: ChartStockBarPaint;
    down: ChartStockBarPaint;
}
type ChartStyleRole = 'axisTitle' | 'categoryAxis' | 'chartArea' | 'dataLabel' | 'dataLabelCallout' | 'dataPoint' | 'dataPoint3D' | 'dataPointLine' | 'dataPointMarker' | 'dataPointWireframe' | 'dataTable' | 'downBar' | 'dropLine' | 'errorBar' | 'floor' | 'gridlineMajor' | 'gridlineMinor' | 'hiLoLine' | 'leaderLine' | 'legend' | 'plotArea' | 'plotArea3D' | 'seriesAxis' | 'seriesLine' | 'title' | 'trendline' | 'trendlineLabel' | 'upBar' | 'valueAxis' | 'wall';
export interface ChartSurfaceBandFormat {
    idx: number;
    style?: ChartExElementStyle | null;
    fill?: SolidFill | GradientFill | PatternFill | null;
    fillHidden?: boolean | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineHidden?: boolean | null;
}
export interface ChartTextBox {
    x: number;
    y: number;
    w: number;
    h: number;
    paragraphs: ChartTextParagraph[];
    verticalAnchor?: 't' | 'ctr' | 'b' | 'just' | 'dist' | string | null;
    wrap?: 'none' | 'square' | string | null;
    lIns?: number;
    tIns?: number;
    rIns?: number;
    bIns?: number;
}
export interface ChartTextParagraph {
    runs: ChartTextRun[];
    align?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string | null;
}
export interface ChartTextRun {
    text: string;
    fontSizeHpt?: number | null;
    bold?: boolean | null;
    italic?: boolean | null;
    color?: string | null;
    colorPaintAuthored?: boolean | null;
    colorHidden?: boolean | null;
    fontFace?: string | null;
    language?: string | null;
    baseline?: number | null;
    paragraphAlign?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string | null;
}
export interface ChartThreeD {
    view3DPresent?: boolean | null;
    rotationX?: number | null;
    rotationXAuthored?: boolean | null;
    rotationY?: number | null;
    rotationYAuthored?: boolean | null;
    heightPercent?: number | null;
    heightPercentAuthored?: boolean | null;
    depthPercent?: number | null;
    depthPercentAuthored?: boolean | null;
    perspective?: number | null;
    perspectiveAuthored?: boolean | null;
    rightAngleAxes?: boolean | null;
    rightAngleAxesAuthored?: boolean | null;
    gapDepthPercent?: number | null;
    gapDepthPercentAuthored?: boolean | null;
    shape?: string | null;
    barGrouping?: 'standard' | 'clustered' | 'stacked' | 'percentStacked' | string | null;
    seriesAxis?: ChartThreeDSeriesAxis | null;
    floor?: ChartThreeDSurface | null;
    sideWall?: ChartThreeDSurface | null;
    backWall?: ChartThreeDSurface | null;
}
export interface ChartThreeDPictureOptions {
    applyToFront?: boolean | null;
    applyToSides?: boolean | null;
    applyToEnd?: boolean | null;
    pictureFormat?: 'stretch' | 'stack' | 'stackScale' | string | null;
    pictureFormatAuthored?: boolean | null;
    pictureStackUnit?: number | null;
    pictureStackUnitAuthored?: boolean | null;
}
export interface ChartThreeDRenderer {
    render(ctx: CanvasRenderingContext2D, chart: ChartModel, rect: ChartRect, ptToPx: number, shapeRotationDeg?: number): boolean;
}
export interface ChartThreeDSeriesAxis {
    title?: string | null;
    hidden: boolean;
    orientation?: 'minMax' | 'maxMin' | string | null;
    tickLabelPos?: string | null;
    tickLabelSkip?: number | null;
    tickMarkSkip?: number | null;
    majorTickMark: string;
    minorTickMark?: string | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    fontFace?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    linePaintAuthored?: boolean | null;
    lineHidden: boolean;
    titleFontSizeHpt?: number | null;
    titleFontBold?: boolean | null;
    titleFontItalic?: boolean | null;
    titleFontColor?: string | null;
    titleFontFace?: string | null;
    titleRotation?: number | null;
    titleVerticalMode?: ChartModel['catAxisTitleVerticalMode'];
    titleManualLayout?: ChartManualLayout | null;
}
export interface ChartThreeDSurface {
    style?: ChartExElementStyle | null;
    fillColor?: string | null;
    fillHidden?: boolean | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden?: boolean | null;
    thicknessPercent?: number | null;
    pictureOptions?: ChartThreeDPictureOptions | null;
}
export interface ChartTrendline {
    name?: string | null;
    trendlineType: string;
    order?: number | null;
    period?: number | null;
    forward?: number | null;
    backward?: number | null;
    intercept?: number | null;
    dispRSqr?: boolean | null;
    dispEq?: boolean | null;
    labelManualLayout?: ChartManualLayout | null;
    labelText?: string | null;
    labelRichRuns?: ChartTextRun[] | null;
    labelFormatCode?: string | null;
    labelFormatSourceLinked?: boolean | null;
    labelFontSizeHpt?: number | null;
    labelFontBold?: boolean | null;
    labelFontItalic?: boolean | null;
    labelFontColor?: string | null;
    labelFontPaintAuthored?: boolean | null;
    labelFontHidden?: boolean | null;
    labelFontFace?: string | null;
    labelFontLanguage?: string | null;
    labelFontBaseline?: number | null;
    labelTextRotation?: number | null;
    labelTextWrap?: string | null;
    labelTextVerticalAnchor?: string | null;
    labelTextVerticalMode?: string | null;
    labelTextLInsEmu?: number | null;
    labelTextTInsEmu?: number | null;
    labelTextRInsEmu?: number | null;
    labelTextBInsEmu?: number | null;
    labelTextBodyAuthored?: boolean | null;
    labelBox?: ChartLabelBox | null;
    labelTextAlign?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden?: boolean | null;
}
export type ChartType = 'line' | 'stackedLine' | 'stackedLinePct' | 'clusteredBar' | 'clusteredBarH' | 'stackedBar' | 'stackedBarH' | 'stackedBarPct' | 'stackedBarHPct' | 'area' | 'stackedArea' | 'stackedAreaPct' | 'pie' | 'doughnut' | 'scatter' | 'bubble' | 'radar' | 'waterfall' | 'stock' | 'surface' | 'surface3D' | 'boxWhisker' | 'sunburst' | 'treemap' | string;
export interface DimOptions {
    color: string;
    opacity: number;
}
export interface DrawingMLCustomDashSegment {
    dash: number;
    space: number;
}
export interface Duotone {
    clr1: string;
    clr2: string;
}
export interface EquationRun {
    type: 'math';
    nodes: MathNode[];
    display: boolean;
    fontSize?: number | null;
    color?: string | null;
}
type ExtensibleLiteral<Known extends string> = Known | (string & Record<never, never>);
export type Fill = SolidFill | NoFill | GradientFill | PatternFill | ImageFill;
export interface FillRect {
    l?: number;
    t?: number;
    r?: number;
    b?: number;
}
export interface FindHighlightColors {
    match?: string;
    active?: string;
}
export interface FindMatch<Loc = unknown> {
    matchIndex: number;
    text: string;
    location: Loc;
}
export interface FindMatchesOptions {
    caseSensitive?: boolean;
}
export interface Glow {
    color: string;
    alpha: number;
    radius: number;
}
export interface GradientFill {
    fillType: 'gradient';
    stops: GradientStop[];
    angle: number;
    gradType: string;
    scaled?: boolean;
    path?: 'shape' | 'circle' | 'rect' | string;
    fillToRect?: FillRect;
    tileRect?: FillRect;
    flip?: 'none' | 'x' | 'y' | 'xy' | string;
    rotWithShape?: boolean;
}
export interface GradientStop {
    position: number;
    color: string;
}
export type HiddenSlideMode = 'show' | 'skip' | 'dim';
export type HyperlinkTarget = {
    kind: 'external';
    url: string;
} | {
    kind: 'internal';
    ref: string;
    slideIndex?: number;
};
export interface ImageFill {
    fillType: 'image';
    imagePath: string;
    svgImagePath?: string;
    mimeType: string;
    dpi?: number;
    rotWithShape?: boolean;
    srcRect?: SrcRect;
    fillRect?: FillRect;
    stretch?: boolean;
    tile?: TileInfo;
    alpha?: number;
    duotone?: Duotone;
}
export function isOoxmlDecodedImageLimitError(error: unknown): error is OoxmlDecodedImageLimitError;
export interface LegendManualLayout {
    xMode?: string;
    yMode?: string;
    wMode?: string;
    hMode?: string;
    x: number;
    y: number;
    w?: number;
    h?: number;
}
export interface LightRig {
    rig: string;
    dir: string;
    rot?: Rot3d;
}
export interface LineBreak {
    type: 'break';
}
export type LoadOptions = LoadOptions__emitterCollision1 & {
    mode?: 'main' | 'worker';
    progressiveLayout?: boolean;
    onLayoutProgress?: (progress: Readonly<ProgressiveLayoutProgress>) => void;
    onLayoutPartial?: (progress: Readonly<ProgressiveLayoutPartial>) => void;
    onLayoutComplete?: (error?: unknown) => void;
};
interface ProgressiveLayoutPartial {
    availableUnits: number;
    totalUnits?: number;
    exact: boolean;
}
interface ProgressiveLayoutProgress {
    committedUnits: number;
}
interface LoadOptions__emitterCollision1 {
    useGoogleFonts?: boolean;
    password?: string;
    wasmUrl?: string | URL;
    maxZipEntryBytes?: number;
    resourceLimits?: OoxmlResourceLimits;
    debug?: boolean;
    onResourceMetrics?: (metrics: OoxmlResourceMetrics) => void;
    workerTimeoutMs?: number;
    math?: MathRenderer;
    threeD?: ChartThreeDRenderer;
    regionMap?: ChartRegionMapRenderer;
    chartEx?: ChartExRenderer;
}
export interface MatchRunSlice {
    runIndex: number;
    start: number;
    end: number;
}
export interface MathAccent {
    kind: 'accent';
    char: string;
    base: MathNode[];
}
export interface MathArray {
    kind: 'array';
    rows: MathNode[][][];
    align: 'eq' | 'center' | 'left';
}
export interface MathBar {
    kind: 'bar';
    pos: 'top' | 'bot';
    base: MathNode[];
}
export interface MathBorderBox {
    kind: 'borderBox';
    hideTop?: boolean;
    hideBot?: boolean;
    hideLeft?: boolean;
    hideRight?: boolean;
    strikeH?: boolean;
    strikeV?: boolean;
    strikeBltr?: boolean;
    strikeTlbr?: boolean;
    base: MathNode[];
}
export interface MathBox {
    kind: 'box';
    base: MathNode[];
}
export interface MathDelimiter {
    kind: 'delimiter';
    begChar: string;
    endChar: string;
    items: MathNode[][];
}
export interface MathFraction {
    kind: 'fraction';
    num: MathNode[];
    den: MathNode[];
    bar?: boolean;
}
export interface MathFunc {
    kind: 'func';
    name: MathNode[];
    arg: MathNode[];
}
export interface MathGroup {
    kind: 'group';
    items: MathNode[];
}
export interface MathGroupChr {
    kind: 'groupChr';
    char: string;
    pos: 'top' | 'bot';
    base: MathNode[];
}
export interface MathLimit {
    kind: 'limit';
    base: MathNode[];
    lower?: MathNode[];
    upper?: MathNode[];
}
export interface MathNary {
    kind: 'nary';
    op: string;
    limLoc?: string;
    sub?: MathNode[];
    sup?: MathNode[];
    body: MathNode[];
}
export type MathNode = MathRun | MathFraction | MathScript | MathNary | MathDelimiter | MathRadical | MathLimit | MathArray | MathGroupChr | MathBar | MathAccent | MathFunc | MathGroup | MathPhant | MathSPre | MathBox | MathBorderBox;
export interface MathPhant {
    kind: 'phant';
    show: boolean;
    zeroWid?: boolean;
    zeroAsc?: boolean;
    zeroDesc?: boolean;
    base: MathNode[];
}
export interface MathRadical {
    kind: 'radical';
    index?: MathNode[];
    radicand: MathNode[];
}
export interface MathRenderer {
    loadMathJax(): Promise<void>;
    mathMLToSvg(mathml: string): Promise<MathSvg>;
}
export interface MathRun {
    kind: 'run';
    text: string;
    style: MathStyle;
}
export interface MathScript {
    kind: 'sup' | 'sub' | 'subSup';
    base: MathNode[];
    sup?: MathNode[];
    sub?: MathNode[];
}
export interface MathSPre {
    kind: 'sPre';
    sub: MathNode[];
    sup: MathNode[];
    base: MathNode[];
}
export type MathStyle = 'roman' | 'italic' | 'bold' | 'boldItalic';
export interface MathSvg {
    svg: string;
    widthEm: number;
    ascentEm: number;
    descentEm: number;
}
export interface MediaElement {
    type: 'media';
    id?: string;
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    mediaKind: 'audio' | 'video';
    posterPath: string;
    posterMimeType: string;
    mediaPath: string;
    mimeType: string;
}
export interface NoFill {
    fillType: 'none';
}
export class OoxmlDecodedImageLimitError extends RangeError {
    readonly metric: OoxmlDecodedImageLimitMetric;
    readonly limit: number;
    readonly observed: number;
    readonly code: 'ooxml-decoded-image-limit';
    constructor(metric: OoxmlDecodedImageLimitMetric, limit: number, observed: number);
}
export type OoxmlDecodedImageLimitMetric = 'image-pixels' | 'active-decoded-bytes';
export class OoxmlError extends Error {
    readonly code: OoxmlErrorCode;
    constructor(code: OoxmlErrorCode, message: string);
}
export type OoxmlErrorCode = 'encrypted' | 'invalid-password' | 'unsupported-encryption' | 'legacy-binary-format' | 'not-ooxml';
export type OoxmlErrorStage = 'container' | 'decompression' | 'parsing' | 'serialization' | 'layout' | 'rendering' | 'worker';
export type OoxmlFormat = 'docx' | 'xlsx' | 'pptx';
export type OoxmlResourceLimit = number | null;
export class OoxmlResourceLimitError extends Error {
    readonly code: 'ooxml-resource-limit';
    readonly details: OoxmlResourceLimitErrorDetails;
    constructor(message: string, details: OoxmlResourceLimitErrorDetails);
}
export interface OoxmlResourceLimitErrorDetails {
    readonly stage: OoxmlErrorStage;
    readonly violation: OoxmlResourceViolation;
}
export interface OoxmlResourceLimits {
    maxArchiveEntryBytes?: OoxmlResourceLimit;
    maxTotalInflatedBytes?: OoxmlResourceLimit;
    maxArchiveEntries?: OoxmlResourceLimit;
}
export type OoxmlResourceMetric = ExtensibleLiteral<'declared-inflated-bytes' | 'actual-inflated-bytes' | 'entry-count' | 'central-directory-bytes' | 'distinct-inflated-bytes' | 'bytes' | 'depth' | 'projected-bytes'>;
export interface OoxmlResourceMetrics {
    readonly schemaVersion: 1;
    readonly scope: 'load' | 'session';
    readonly format: OoxmlFormat;
    readonly mode: 'main' | 'worker' | 'node';
    readonly status: 'ok' | 'error';
    readonly sourceBytes?: number;
    readonly elapsedMs: number;
    readonly policy: Readonly<OoxmlResourcePolicySnapshot>;
    readonly usage?: OoxmlResourceUsageSnapshot;
    readonly checkpoints: readonly OoxmlResourceMetricsCheckpoint[];
    readonly outcome?: Readonly<Record<string, number>>;
    readonly error?: Readonly<{
        readonly code?: string;
        readonly stage?: string;
        readonly resource?: string;
        readonly metric?: string;
    }>;
}
export interface OoxmlResourceMetricsCheckpoint {
    readonly name: string;
    readonly elapsedMs: number;
    readonly usage?: OoxmlResourceUsageSnapshot;
}
export type OoxmlResourceName = ExtensibleLiteral<'archive' | 'archive-entry' | 'xml-event' | 'xml-context' | 'xml-tree' | 'worksheet-row' | 'worksheet-shell'>;
export interface OoxmlResourcePolicySnapshot {
    readonly maxArchiveEntryBytes: number | null;
    readonly maxTotalInflatedBytes: number | null;
    readonly maxArchiveEntries: number | null;
}
export interface OoxmlResourceUsageSnapshot {
    readonly archiveEntryCount: number;
    readonly declaredInflatedBytes: number;
    readonly largestInflatedEntryBytes?: number;
    readonly distinctInflatedBytes: number;
    readonly operationInflatedBytes: number;
}
export interface OoxmlResourceViolation {
    readonly format: OoxmlFormat;
    readonly operation: string;
    readonly resource: OoxmlResourceName;
    readonly metric: OoxmlResourceMetric;
    readonly part?: string;
    readonly limit: number;
    readonly observed: number;
    readonly configurable: boolean;
    readonly usage: OoxmlResourceUsageSnapshot;
}
export function openExternalHyperlink(url: string, allowed?: readonly string[], win?: Pick<Window, 'open'> | undefined): boolean;
export interface Paragraph extends Paragraph__emitterCollision1 {
    eaLnBrk: boolean;
    defTabSz?: number;
}
interface Paragraph__emitterCollision1 {
    alignment: string;
    marL: number;
    marR: number;
    indent: number;
    spaceBefore: number | null;
    spaceAfter: number | null;
    spaceLine: SpaceLine | null;
    lvl: number;
    bullet: Bullet__emitterCollision1;
    defFontSize: number | null;
    defColor: string | null;
    defBold: boolean | null;
    defItalic: boolean | null;
    defFontFamily: string | null;
    tabStops: TabStop[];
    rtl?: boolean;
    runs: TextRun[];
}
export type PathCmd = {
    cmd: 'moveTo';
    x: number;
    y: number;
} | {
    cmd: 'lineTo';
    x: number;
    y: number;
} | {
    cmd: 'cubicBezTo';
    x1: number;
    y1: number;
    x2: number;
    y2: number;
    x: number;
    y: number;
} | {
    cmd: 'quadBezTo';
    x1: number;
    y1: number;
    x: number;
    y: number;
} | {
    cmd: 'arcTo';
    wr: number;
    hr: number;
    stAng: number;
    swAng: number;
} | {
    cmd: 'close';
};
export interface PatternFill {
    fillType: 'pattern';
    fg: string;
    bg: string;
    preset: string;
}
export interface PictureElement {
    type: 'picture';
    id?: string;
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    imagePath: string;
    mimeType: string;
    svgImagePath?: string;
    intrinsicWidthPx?: number;
    intrinsicHeightPx?: number;
    stroke: Stroke | null;
    prstGeom?: string;
    prstAdjust?: number[];
    srcRect?: {
        l: number;
        t: number;
        r: number;
        b: number;
    };
    alpha?: number;
    duotone?: Duotone;
    custGeom?: PathCmd[][] | null;
    shadow?: Shadow;
    innerShadow?: Shadow;
    glow?: Glow;
    softEdge?: SoftEdge;
    reflection?: Reflection;
    scene3d?: Scene3d;
    sp3d?: Sp3d;
}
export type PptxCommentAnchor = Readonly<{
    type: 'slide';
}> | Readonly<{
    type: 'drawingElement';
    elementId?: string;
    creationId?: string;
}> | Readonly<{
    type: 'textRange';
    elementId?: string;
    start?: number;
    length?: number;
}> | Readonly<{
    type: 'unknown';
}>;
export interface PptxComment {
    authorId?: number;
    modernAuthorId?: string;
    id?: string;
    index?: number;
    author?: string;
    date?: string;
    x?: number;
    y?: number;
    anchors?: readonly Readonly<PptxCommentAnchor>[];
    status?: 'active' | 'resolved' | 'closed';
    text: string;
    replies?: readonly Readonly<PptxCommentReply>[];
}
export interface PptxCommentReply {
    id?: string;
    authorId?: string;
    author?: string;
    date?: string;
    status?: 'active' | 'resolved' | 'closed';
    text: string;
}
export interface PptxCommentSelectionContext {
    readonly format: 'pptx';
    readonly kind: 'comment';
    readonly slideIndex: number;
    readonly commentIndex: number;
    readonly occurrenceId: string;
    readonly commentId?: string;
    readonly point?: Readonly<{
        x: number;
        y: number;
    }>;
    readonly thread: ViewerCommentThreadContext;
    readonly truncated: boolean;
    readonly truncationReasons: readonly 'text'[];
    readonly textCharacters: number;
    readonly maxTextCharacters: number;
}
export interface PptxCommentsOptions extends ViewerCommentsOptions {
    readonly cards?: boolean;
    readonly side?: 'auto' | 'left' | 'right';
    readonly markers?: boolean;
    readonly connectors?: ViewerCommentConnectorOptions;
}
export interface PptxElementBounds {
    readonly elementId: string;
    readonly elementIndex: number;
    readonly origin: SlideElementOrigin | 'unknown';
    readonly elementType: SlideElement['type'];
    readonly bounds: PptxElementContext['bounds'];
}
export interface PptxElementContext {
    readonly format: 'pptx';
    readonly kind: 'element';
    readonly slideIndex: number;
    readonly elementIndex: number;
    readonly origin: SlideElementOrigin | 'unknown';
    readonly elementType: SlideElement['type'];
    readonly point: PptxSlidePoint;
    readonly bounds: Readonly<{
        x: number;
        y: number;
        width: number;
        height: number;
        rotation: number;
        flipH: boolean;
        flipV: boolean;
    }>;
    readonly shapeId?: string;
    readonly name?: string;
    readonly geometry?: string;
    readonly text?: string;
    readonly mimeType?: string;
    readonly mediaKind?: 'audio' | 'video';
    readonly rowCount?: number;
    readonly columnCount?: number;
    readonly seriesCount?: number;
    readonly truncated: boolean;
    readonly truncationReasons: readonly 'text'[];
    readonly textCharacters: number;
    readonly maxTextCharacters: number;
}
export interface PptxElementContextOptions {
    readonly tolerance?: number;
    readonly maxTextCharacters?: number;
}
export type PptxHighlightColors = FindHighlightColors;
export interface PptxHighlightMatch {
    slices: MatchRunSlice[];
    active: boolean;
}
export interface PptxMatchLocation {
    slide: number;
}
export class PptxPresentation {
    static load(source: string | ArrayBuffer, opts?: LoadOptions): Promise<PptxPresentation>;
    get slideCount(): number;
    get availableSlideCount(): number;
    get layoutComplete(): boolean;
    waitUntilLayoutComplete(): Promise<void>;
    get slideWidth(): number;
    get slideHeight(): number;
    get mode(): 'main' | 'worker';
    getNotes(slideIndex: number): string | null;
    getComments(slideIndex: number): readonly Readonly<PptxComment>[];
    isHidden(slideIndex: number): boolean;
    getSlideIndexByPartName(partName: string): number | undefined;
    resolveInternalTarget(ref: string, currentIndex?: number): number | undefined;
    renderSlide(canvas: HTMLCanvasElement | OffscreenCanvas, slideIndex: number, opts?: RenderSlideOptions): Promise<void>;
    renderSlideToBitmap(slideIndex: number, opts?: RenderSlideToBitmapOptions): Promise<ImageBitmap>;
    collectSlideRuns(slideIndex: number, width?: number): Promise<PptxTextRunInfo[]>;
    getElementContextAt(slideIndex: number, point: PptxSlidePoint, options?: PptxElementContextOptions): Promise<PptxElementContext | null>;
    getElementBoundsByIds(slideIndex: number, elementIds: readonly string[]): Promise<readonly PptxElementBounds[]>;
    getMedia(mediaPath: string): Promise<Blob>;
    getImage(imagePath: string, mimeType: string): Promise<Blob>;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    toMarkdown(): Promise<string>;
    presentSlide(canvas: HTMLCanvasElement, slideIndex: number, opts?: PresentSlideOptions): Promise<PresentationHandle>;
    toEditorPresentation(): Promise<Presentation>;
    destroy(): void;
    private __privatePresence;
    private constructor();
}
export class PptxScrollViewer implements ZoomableViewer {
    static fromPresentation(container: HTMLElement, presentation: PptxPresentation, opts?: Omit<PptxScrollViewerOptions, keyof LoadOptions>): Omit<PptxScrollViewer, 'load'>;
    constructor(container: HTMLElement, opts?: PptxScrollViewerOptions);
    load(source: string | ArrayBuffer): Promise<void>;
    get slideCount(): number;
    get availableSlideCount(): number;
    get layoutComplete(): boolean;
    waitUntilLayoutComplete(): Promise<void>;
    relayout(): void;
    setScale(scale: number): void;
    getScale(): number;
    zoomIn(): void;
    zoomOut(): void;
    fitWidth(): void;
    fitPage(): void;
    scrollToSlide(index: number, opts?: {
        behavior?: 'auto' | 'smooth';
    }): void;
    goToComment(slideIndex: number, commentIndex: number, opts?: {
        behavior?: 'auto' | 'smooth';
    }): Promise<boolean>;
    findText(query: string, opts?: FindMatchesOptions): Promise<FindMatch<PptxMatchLocation>[]>;
    findNext(): Promise<FindMatch<PptxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<PptxMatchLocation> | null>;
    clearFind(): void;
    get topVisibleSlide(): number;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    getSelectionContext(options?: PptxSelectionContextOptions): PptxSelectionContext | null;
    destroy(): void;
    private __privatePresence;
}
export interface PptxScrollViewerOptions extends Pick<RenderSlideOptions, 'width' | 'dpr'>, LoadOptions {
    width?: number;
    gap?: number;
    paddingTop?: number;
    paddingBottom?: number;
    paddingLeft?: number;
    paddingRight?: number;
    overscan?: number;
    enableTextSelection?: boolean;
    comments?: boolean | PptxCommentsOptions;
    enableElementSelection?: boolean;
    elementHitTolerance?: number;
    onSelectionContextChange?: (context: PptxSelectionContext | null) => void;
    onContextMenu?: (event: ViewerContextMenuEvent<PptxSelectionContext>) => void;
    findHighlightColors?: FindHighlightColors;
    enableMediaPlayback?: boolean;
    mediaOverscan?: number;
    zoomMin?: number;
    zoomMax?: number;
    enableZoom?: boolean;
    refitOnResize?: boolean;
    background?: string;
    pageShadow?: string | false;
    onVisibleSlideChange?: (topIndex: number, total: number, layoutComplete: boolean) => void;
    onScaleChange?: (scale: number) => void;
    onError?: (err: Error) => void;
    onHyperlinkClick?: (target: HyperlinkTarget) => void;
    enableHyperlinks?: boolean;
}
export type PptxSelectionContext = PptxTextSelectionContext | PptxCommentSelectionContext | PptxElementContext;
export type PptxSelectionContextOptions = TextSelectionContextOptions;
export interface PptxSelectionRunLocator {
    readonly slideIndex: number;
    readonly runIndex: number;
    readonly shapeId?: string;
    readonly elementIndex?: number;
    readonly origin?: SlideElementOrigin;
}
export interface PptxSlidePoint {
    readonly x: number;
    readonly y: number;
}
export interface PptxTextRunInfo {
    elementIndex?: number;
    origin?: SlideElementOrigin;
    shapeId?: string;
    text: string;
    inShapeX: number;
    inShapeY: number;
    w: number;
    h: number;
    fontSize: number;
    font: string;
    shapeX: number;
    shapeY: number;
    shapeW: number;
    shapeH: number;
    rotation: number;
    textBodyRotation?: number;
    hyperlink?: HyperlinkTarget;
}
export interface PptxTextSelectionContext {
    readonly format: 'pptx';
    readonly kind: 'text';
    readonly text: string;
    readonly slideIndexes: readonly number[];
    readonly shapeIds: readonly string[];
    readonly runs: readonly PptxSelectionRunLocator[];
    readonly truncated: boolean;
    readonly truncationReasons: readonly ('text' | 'runs')[];
    readonly textCharacters: number;
    readonly maxTextCharacters: number;
    readonly maxRunLocators: number;
}
export class PptxViewer implements ZoomableViewer {
    static fromPresentation(canvas: HTMLCanvasElement, presentation: PptxPresentation, opts?: Omit<PptxViewerOptions, keyof LoadOptions>): Omit<PptxViewer, 'load'>;
    constructor(canvas: HTMLCanvasElement, opts?: PptxViewerOptions);
    load(source: string | ArrayBuffer): Promise<void>;
    goToSlide(index: number): Promise<void>;
    nextSlide(): Promise<void>;
    prevSlide(): Promise<void>;
    setHiddenSlideMode(mode: HiddenSlideMode): Promise<void>;
    get hiddenSlideMode(): HiddenSlideMode;
    get visibleSlideCount(): number;
    get slideIndex(): number;
    get slideCount(): number;
    get availableSlideCount(): number;
    get layoutComplete(): boolean;
    waitUntilLayoutComplete(): Promise<void>;
    getNotes(slideIndex: number): string | null;
    get canvasElement(): HTMLCanvasElement;
    getScale(): number;
    setScale(scale: number): Promise<void>;
    zoomIn(): Promise<void>;
    zoomOut(): Promise<void>;
    fitWidth(): Promise<void>;
    fitPage(): Promise<void>;
    findText(query: string, opts?: FindMatchesOptions): Promise<FindMatch<PptxMatchLocation>[]>;
    findNext(): Promise<FindMatch<PptxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<PptxMatchLocation> | null>;
    clearFind(): void;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    getSelectionContext(options?: PptxSelectionContextOptions): PptxSelectionContext | null;
    destroy(): void;
    private __privatePresence;
}
export interface PptxViewerOptions extends Pick<RenderOptions, 'width' | 'dpr'>, LoadOptions {
    onSlideChange?: (index: number, total: number, layoutComplete: boolean) => void;
    onError?: (err: Error) => void;
    zoomMin?: number;
    zoomMax?: number;
    onScaleChange?: (scale: number) => void;
    enableMediaPlayback?: boolean;
    enableTextSelection?: boolean;
    enableElementSelection?: boolean;
    elementHitTolerance?: number;
    onSelectionContextChange?: (context: PptxSelectionContext | null) => void;
    onContextMenu?: (event: ViewerContextMenuEvent<PptxSelectionContext>) => void;
    findHighlightColors?: FindHighlightColors;
    hiddenSlideMode?: HiddenSlideMode;
    hiddenSlideDim?: Partial<DimOptions>;
    onHyperlinkClick?: (target: HyperlinkTarget) => void;
    enableHyperlinks?: boolean;
}
export interface Presentation {
    slideWidth: number;
    slideHeight: number;
    slides: Slide[];
    defaultTextColor: string | null;
    majorFont: string | null;
    minorFont: string | null;
    hlinkColor?: string;
    folHlinkColor?: string;
}
export interface PresentationHandle {
    play(mediaPath?: string): void;
    pause(mediaPath?: string): void;
    destroy(): void;
}
export interface PresentSlideOptions extends Omit<RenderSlideOptions, 'skipMediaControls'> {
    onError?: (error: Error) => void;
}
export function readPptxTextSelectionContext(root: HTMLElement, selection: Selection | null, options?: TextSelectionContextOptions): PptxTextSelectionContext | null;
export interface Reflection {
    blur: number;
    dist: number;
    dir: number;
    stA: number;
    stPos: number;
    endA: number;
    endPos: number;
    sx: number;
    sy: number;
}
export interface RenderOptions {
    width?: number;
    defaultTextColor?: string | null;
    dpr?: number;
    majorFont?: string | null;
    minorFont?: string | null;
    hlinkColor?: string | null;
    fetchMedia?: (path: string) => Promise<Blob>;
    fetchImage?: (path: string, mimeType: string) => Promise<Blob>;
    skipMediaControls?: boolean;
}
export function renderSlide(canvas: HTMLCanvasElement | OffscreenCanvas, slide: Slide, slideWidth: number, slideHeight: number, opts?: SlideRenderOptions, onTextRun?: TextRunCallback): Promise<HTMLCanvasElement | OffscreenCanvas>;
export interface RenderSlideOptions {
    width?: number;
    dpr?: number;
    onTextRun?: TextRunCallback;
    skipMediaControls?: boolean;
    dim?: DimOptions;
}
export interface RenderSlideToBitmapOptions {
    width?: number;
    dpr?: number;
    dim?: DimOptions;
    onTextRun?: TextRunCallback;
}
export interface Rot3d {
    lat: number;
    lon: number;
    rev: number;
}
export interface Scene3d {
    camera: Camera3d;
    lightRig?: LightRig;
}
export interface SecondaryValueAxis {
    min: number | null;
    max: number | null;
    title: string | null;
    hidden: boolean;
    formatCode?: string | null;
    displayUnits?: ChartDisplayUnits | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    fontItalic?: boolean | null;
    fontBold?: boolean | null;
    fontFace?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden: boolean;
    majorTickMark: string;
    minorTickMark?: string | null;
    minorGridlines?: boolean;
    minorGridlineColor?: string | null;
    minorGridlineWidthEmu?: number | null;
    minorGridlineDash?: string | null;
    majorGridlines?: boolean;
    majorGridlineColor?: string | null;
    majorGridlineWidthEmu?: number | null;
    majorGridlineDash?: string | null;
    majorUnit?: number | null;
    minorUnit?: number | null;
    logBase?: number | null;
    orientation?: 'minMax' | 'maxMin' | string | null;
    tickLabelPos?: string | null;
    labelAlignment?: 'l' | 'ctr' | 'r' | null;
    labelOffsetPercent?: number | null;
    tickLabelSkip?: number | null;
    tickMarkSkip?: number | null;
    crosses?: string | null;
    crossesAt?: number | null;
    titleFontSizeHpt?: number | null;
    titleFontBold?: boolean | null;
    titleFontItalic?: boolean | null;
    titleFontColor?: string | null;
    titleFontFace?: string | null;
    titleRotation?: number | null;
    titleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    titleManualLayout?: ChartManualLayout | null;
}
export interface Shadow {
    color: string;
    alpha: number;
    blur: number;
    dist: number;
    dir: number;
    sx?: number;
    sy?: number;
    kx?: number;
    ky?: number;
    algn?: 'tl' | 't' | 'tr' | 'l' | 'ctr' | 'r' | 'bl' | 'b' | 'br';
    rotWithShape?: boolean;
}
export interface ShapeElement {
    type: 'shape';
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    geometry: string;
    fill: Fill | null;
    stroke: Stroke | null;
    textBody: TextBody | null;
    defaultTextColor: string | null;
    custGeom: PathCmd[][] | null;
    adj: number | null;
    adj2: number | null;
    adj3: number | null;
    adj4: number | null;
    adj5: number | null;
    adj6: number | null;
    adj7: number | null;
    adj8: number | null;
    shadow: Shadow | null;
    innerShadow?: Shadow;
    glow?: Glow;
    softEdge?: SoftEdge;
    reflection?: Reflection;
    textRect?: TextRect;
    scene3d?: Scene3d;
    sp3d?: Sp3d;
    id?: string;
    name?: string;
    hyperlink?: string;
    hyperlinkAction?: string;
}
export interface Slide {
    index: number;
    slideNumber: number;
    partName?: string;
    background: Fill | null;
    elements: SlideElement[];
    elementSources?: SlideElementSource[];
    notes?: string;
    comments?: PptxComment[];
    hidden?: boolean;
    parseError?: string;
}
export type SlideElement = ShapeElement | PictureElement | TableElement | ChartElement | MediaElement;
export type SlideElementOrigin = 'master' | 'layout' | 'slide';
export interface SlideElementSource {
    origin: SlideElementOrigin;
}
export type SlideRenderOptions = RenderOptions & {
    math?: MathRenderer;
    threeD?: ChartThreeDRenderer;
    regionMap?: ChartRegionMapRenderer;
    chartEx?: ChartExRenderer;
    dim?: DimOptions;
};
export interface SoftEdge {
    radius: number;
}
export interface SolidFill {
    fillType: 'solid';
    color: string;
}
export interface Sp3d {
    z?: number;
    extrusionH?: number;
    contourW?: number;
    contourClr?: string;
    extrusionClr?: string;
    prstMaterial: string;
    bevelT?: Bevel3d;
    bevelB?: Bevel3d;
}
export type SpaceLine = {
    type: 'pct';
    val: number;
} | {
    type: 'pts';
    val: number;
};
export interface SrcRect {
    l: number;
    t: number;
    r: number;
    b: number;
}
export interface Stroke {
    color: string;
    width: number;
    fill?: Exclude<Fill, {
        fillType: 'image';
    } | {
        fillType: 'none';
    }>;
    dashStyle?: string;
    customDash?: ReadonlyArray<DrawingMLCustomDashSegment>;
    lineCap?: 'butt' | 'round' | 'square';
    lineJoin?: 'round' | 'bevel' | 'miter';
    miterLimit?: number;
    alignment?: 'ctr' | 'in';
    headEnd?: ArrowEnd;
    tailEnd?: ArrowEnd;
    cmpd?: string;
}
export interface TableCell {
    textBody: TextBody | null;
    fill: Fill | null;
    textColor?: string;
    borderL: Stroke | null;
    borderR: Stroke | null;
    borderT: Stroke | null;
    borderB: Stroke | null;
    diagonalTL?: Stroke | null;
    diagonalTR?: Stroke | null;
    gridSpan: number;
    rowSpan: number;
    hMerge: boolean;
    vMerge: boolean;
}
export interface TableElement {
    type: 'table';
    id?: string;
    x: number;
    y: number;
    width: number;
    height: number;
    rotation: number;
    flipH: boolean;
    flipV: boolean;
    cols: number[];
    rows: TableRow[];
    rtl?: boolean;
}
export interface TableRow {
    height: number;
    cells: TableCell[];
}
export interface TabStop {
    pos: number;
    algn: string;
}
export interface TextBody extends TextBody__emitterCollision1 {
    rtlCol?: boolean;
    textWarp?: {
        preset: string;
        adj?: number[];
    };
    paragraphs: Paragraph[];
}
interface TextBody__emitterCollision1 {
    verticalAnchor: string;
    paragraphs: Paragraph__emitterCollision1[];
    defaultFontSize: number | null;
    defaultBold: boolean | null;
    defaultItalic: boolean | null;
    lIns: number;
    rIns: number;
    tIns: number;
    bIns: number;
    wrap: string;
    vert: string;
    autoFit: string;
    fontScale?: number | null;
    lnSpcReduction?: number | null;
    numCol?: number;
    spcCol?: number;
}
export interface TextOutline {
    width: number;
    color?: string;
}
export interface TextRect {
    x: number;
    y: number;
    width: number;
    height: number;
}
export type TextRun = TextRunData | LineBreak | EquationRun;
export type TextRunCallback = (run: PptxTextRunInfo) => void;
export interface TextRunData {
    type: 'text';
    text: string;
    bold: boolean | null;
    italic: boolean | null;
    underline: boolean;
    underlineStyle?: string;
    underlineColor?: string;
    strikethrough: boolean;
    strikeDouble?: boolean;
    fontSize: number | null;
    color: string | null;
    fontFamily: string | null;
    fontFamilyEa?: string;
    fontFamilySym?: string;
    baseline?: number;
    caps?: 'none' | 'small' | 'all';
    letterSpacing?: number;
    fieldType?: string;
    hyperlink?: string;
    hyperlinkAction?: string;
    shadow?: Shadow;
    reflection?: Reflection;
    outline?: TextOutline;
    highlight?: string;
}
export interface TextSelectionContextOptions {
    readonly maxTextCharacters?: number;
    readonly maxRunLocators?: number;
}
export interface TileInfo {
    tx?: number;
    ty?: number;
    sx?: number;
    sy?: number;
    flip?: string;
    algn?: string;
}
export interface ViewerCommentConnectorOptions {
    readonly route?: ViewerCommentConnectorRoute;
    readonly stroke?: ViewerCommentConnectorStroke;
    readonly color?: string;
    readonly activeColor?: string;
}
export type ViewerCommentConnectorRoute = 'bezier' | 'orthogonal';
export type ViewerCommentConnectorStroke = 'solid' | 'dashed';
export interface ViewerCommentMessageContext {
    readonly id?: string;
    readonly author?: string;
    readonly date?: string;
    readonly text: string;
    readonly status?: 'active' | 'resolved' | 'closed';
}
interface ViewerCommentsOptions {
    readonly includeResolved?: boolean;
}
export interface ViewerCommentThreadContext {
    readonly root: ViewerCommentMessageContext;
    readonly replies: readonly ViewerCommentMessageContext[];
}
export interface ViewerContextMenuEvent<TContext> {
    readonly originalEvent: MouseEvent;
    getContext(): Promise<TContext | null>;
}
export interface ZoomableViewer {
    getScale(): number;
    setScale(scale: number): void | Promise<void>;
    zoomIn(): void | Promise<void>;
    zoomOut(): void | Promise<void>;
    fitWidth(): void | Promise<void>;
    fitPage(): void | Promise<void>;
}
