import { normalizeReferenceFamily } from '@silurus/ooxml-core/internal/reference-font-identity';
import data from './font-route-data.json';
/** All-alias, source-aware family classification generated by the single core
 * reducer. This lightweight preflight owner carries no metrics/repertoires or
 * resource certainty. Keys are bounded by the catalogue, never caller queries.
 * Bits: FarEast1, PANOSEserif2, basicCJKunknown0/false4/true8. */
const routes = new Map(data.routes as [string, number][]);
export function referenceFontRoute(family: string): number {
  return routes.get(normalizeReferenceFamily(family)) ?? 0;
}
