#!/usr/bin/env python3
"""Generate the bounded canonical-static-v1 script admission profile.

Inputs, in order: Unicode 17 Scripts/IndicSyllabicCategory, Unicode 16
Scripts/IndicSyllabicCategory/IndicPositionalCategory/Blocks, HarfBuzz 11.0.0
gen-indic-table.py and hb-ot-shaper.hh. Downloaded sources are not shipped.
"""
import contextlib
import hashlib
import io
import re
import runpy
import sys
from pathlib import Path

hashes = [
    '9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf',
    '3fc122f4cf58b0c19268d5f810263b04ab4e1e67743386ec0e0ada9c76aec5be',
    '9e88f0a677df47311106340be8ede2ecdacd9c1c931831218d2be6d5508e0039',
    '615f1b92ba7ec76e18c5b5c05d2e1836e4b98bc791eb9e27946c7621fc047ae7',
    'cbb9e2193e26c9b3d595a8f0ff4fd2ad956482309143ceb4ce5469c19f14feba',
    'f3907b395d410f1b97342292ca6bc83dd12eb4b205f2a0c48efdef99e517d7b0',
    'c9303dd44599e23fe8a66b353e699811836460be7d5d9d8889be3cf939dd0e40',
    'cee53ee08f5958a9c42e91386a1939fdfaf4c930fe7c41e51eba35e5d53df484',
]
paths = [Path(value) for value in sys.argv[1:]]
raw = [path.read_bytes() for path in paths]
if len(raw) != len(hashes) or [hashlib.sha256(value).hexdigest() for value in raw] != hashes:
    raise ValueError('Expected pinned Unicode/HarfBuzz sources')

def properties(data):
    result = {}
    for line in data.decode().splitlines():
        fields = line.split('#')[0].strip().split(';')
        if len(fields) < 2:
            continue
        ends = fields[0].strip().split('..')
        for cp in range(int(ends[0], 16), int(ends[-1], 16) + 1):
            result[cp] = fields[1].strip()
    return result

scripts, isc, old_scripts, old_isc = [properties(value) for value in raw[:4]]
sys.argv = [str(paths[6]), str(paths[3]), str(paths[4]), str(paths[5])]
with contextlib.redirect_stdout(io.StringIO()):
    hb = runpy.run_path(str(paths[6]))['indic_data']
special = set(re.findall(r'case HB_SCRIPT_(\w+):', raw[7].decode()))
indic = ['Bengali', 'Devanagari', 'Gujarati', 'Gurmukhi', 'Kannada',
         'Malayalam', 'Oriya', 'Tamil', 'Telugu', 'Myanmar']
modes = {script: index + 1 for index, script in enumerate(indic)}
modes['Hangul'] = 11
profile = {cp: modes.get(script, 12 if script.upper() in special else 0)
           for cp, script in scripts.items()}
roles = {}
for cp, script in scripts.items():
    if script not in indic or old_scripts.get(cp) != script or old_isc.get(cp) != isc.get(cp):
        continue
    category = hb.get(cp, ('X',))[0]
    if isc.get(cp) == 'Consonant' and category in {'C', 'Ra'}:
        roles[cp] = 1
    elif isc.get(cp) == 'Vowel_Dependent' and category in (
            {'VPre', 'VAbv', 'VBlw', 'VPst', 'A'} if script == 'Myanmar' else {'M', 'MPst'}):
        roles[cp] = 2

def ranges(values):
    result = []
    for cp, value in sorted(values.items()):
        if value == 0:
            continue
        if result and result[-1][1] + 1 == cp and result[-1][2] == value:
            result[-1][1] = cp
        else:
            result.append([cp, cp, value])
    return result

out = '''/** canonical-static-v1 admission: HarfBuzz 11.0.0 script dispatch and
 * exact generated Indic/Myanmar categories, intersected with Unicode 16/17
 * script/ISC agreement. Generated by generate-font-shaping-profile.py.
 * Sources: unicode.org/Public/{16,17}.0.0/ucd and
 * github.com/harfbuzz/harfbuzz/tree/11.0.0/src; SHA-256 in input order:
''' + ''.join(' * ' + value + '\n' for value in hashes) + ''' * Mode 0=default; 1–9=nine Indic scripts; 10=Myanmar; 11=Hangul;
 * 12=unimplemented script transforms. Roles 1=consonant, 2=dependent vowel.
 * This is a library profile, not detected browser shaping capability. */
'''
for name, data in [('SHAPING_SCRIPT_RANGES', profile), ('SIMPLE_SYLLABLE_ROLES', roles)]:
    out += f'export const {name}: readonly number[] = [\n'
    out += ''.join('  ' + ', '.join(hex(value) for value in row) + ',\n' for row in ranges(data))
    out += '];\n'
(Path(__file__).resolve().parent.parent / 'packages/core/src/internal/font-shaping-profile-data.ts').write_text(out)
