"""Generate the UAX #15 blocking classes used for font-resource attribution.

Usage: python3 scripts/generate-canonical-combining-class.py UnicodeData.txt
Input: https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
"""
import sys
import hashlib
from pathlib import Path

raw = Path(sys.argv[1]).read_bytes()
expected_hash = '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'
if hashlib.sha256(raw).hexdigest() != expected_hash:
    raise ValueError('Expected the pinned Unicode 17.0.0 UnicodeData.txt')
ranges = []
for line in raw.decode().splitlines():
    fields = line.split(';')
    cp, cls = int(fields[0], 16), int(fields[3])
    if not cls:
        continue
    if ranges and ranges[-1][1] + 1 == cp and ranges[-1][2] == cls:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp, cls])

target = Path(__file__).resolve().parent.parent / 'packages/core/src/internal/canonical-combining-class.ts'
target.write_text('''/** Unicode 17.0.0 UnicodeData.txt field 3, merged equal-class ranges.
 * https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
 * SHA-256: 2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c
 * UAX #15 canonical composition needs these classes to honor blocking,
 * including class-zero marks. All omitted scalars have class zero.
 * Generated by scripts/generate-canonical-combining-class.py. */
const RANGES: readonly number[] = [
''' + ''.join(f'  0x{a:x}, 0x{b:x}, {c},\n' for a, b, c in ranges) + '''];

export function canonicalCombiningClass(cp: number): number {
  let lo = 0;
  let hi = RANGES.length / 3 - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    const index = mid * 3;
    if (cp < RANGES[index]) hi = mid - 1;
    else if (cp > RANGES[index + 1]) lo = mid + 1;
    else return RANGES[index + 2];
  }
  return 0;
}
''')
