#!/usr/bin/env python3
"""Pinned Unicode authority for NFC display and font-aware support analysis.

Usage: generate-canonical-font-data.py UnicodeData.txt CompositionExclusions.txt
       DerivedCoreProperties.txt
Sources: https://www.unicode.org/Public/17.0.0/ucd/ ; Unicode license in core.
Direct decompositions are shaping execution edges, not equivalent-spelling search.
"""
import hashlib
import sys
from pathlib import Path

hashes = ['2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c',
          '2f239196ef3b5b61db5cc476e9bd80f534d15aa1b74e1be1dea5d042a344c85f',
          '24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08']
raw = [Path(p).read_bytes() for p in sys.argv[1:]]
if len(raw) != 3 or [hashlib.sha256(b).hexdigest() for b in raw] != hashes:
    raise ValueError('Expected pinned Unicode 17.0.0 sources')
exclusions = {int(s.split('#')[0].strip(), 16) for s in raw[1].decode().splitlines()
              if s.split('#')[0].strip()}
rows = [s.split(';') for s in raw[0].decode().splitlines()]
classes = {int(r[0], 16): int(r[3]) for r in rows}
decompositions = []
compositions = []
marks = []
assigned = []
def append_range(target, start, end):
    if target and target[-1][1] + 1 == start:
        target[-1][1] = end
    else:
        target.append([start, end])
start = None
for r in rows:
    cp = int(r[0], 16)
    if r[1].endswith(', First>'):
        start = cp
        continue
    first = start if r[1].endswith(', Last>') else cp
    start = None
    if r[2] != 'Cs':
        append_range(assigned, first, cp)
    if r[2].startswith('M'):
        append_range(marks, first, cp)
    decomp = r[5]
    if decomp and not decomp.startswith('<'):
        points = [int(s, 16) for s in decomp.split()]
        if len(points) > 2:
            raise ValueError('Unexpected direct decomposition arity')
        decompositions.append([cp, *points, *([0] if len(points) == 1 else [])])
        if len(points) == 2 and cp not in exclusions and classes.get(points[0], 0) == 0:
            compositions.append([*points, cp])
ignorables = []
for line in raw[2].decode().splitlines():
    s = line.split('#')[0].strip()
    if not s:
        continue
    domain, prop = [v.strip() for v in s.split(';')[:2]]
    if prop == 'Default_Ignorable_Code_Point':
        pair = domain.split('..')
        append_range(ignorables, int(pair[0], 16), int(pair[-1], 16))

out = '''/** Unicode 17.0.0 fixed NFC authority (UAX #15).
 * Generated by scripts/generate-canonical-font-data.py from UnicodeData,
 * CompositionExclusions and DerivedCoreProperties. Source SHA-256 hashes:
''' + ''.join(' * ' + h + '\n' for h in hashes) + ''' * https://www.unicode.org/Public/17.0.0/ucd/ ; Unicode license in core.
 * Direct decompositions deliberately retain intermediate nodes. */
export const CANONICAL_UNICODE_VERSION = '17.0.0';
'''
for name, data in [('DECOMPOSITIONS', decompositions), ('COMPOSITIONS', sorted(compositions)),
                   ('MARK_RANGES', marks), ('ASSIGNED_RANGES', assigned), ('IGNORABLE_RANGES', ignorables)]:
    out += f'export const {name}: readonly number[] = [\n'
    out += ''.join('  ' + ', '.join(hex(v) for v in row) + ',\n' for row in data)
    out += '];\n'
(Path(__file__).resolve().parent.parent / 'packages/core/src/internal/canonical-font-data.ts').write_text(out)
