#!/usr/bin/env python3
"""Generate the character repertoires of PowerPoint's default East Asian faces.

When a run's East Asian slot has no face, PowerPoint draws the East Asian
characters in an application-default face chosen from the Latin face's serif
class (issue #1627): serif -> MS Mincho, PMingLiU, Batang; sans -> MS Gothic,
Microsoft JhengHei, Malgun Gothic. PowerPoint's reference PDF engine used the
first default face whose repertoire covered the whole run: "繁體中文" stayed in
MS Mincho/MS Gothic, "简体中文" moved entirely to PMingLiU/Microsoft JhengHei
(MS Mincho lacks 简), and Hangul moved to Batang/Malgun Gothic.

The renderer only needs the repertoire of the first two tiers over the code
points it draws in the East Asian slot. MS Mincho and MS Gothic share one
repertoire (checked here); PMingLiU and Microsoft JhengHei are stored as range
lists. No outlines or metrics are written.

Run: uv run --with fonttools python scripts/generate-pptx-east-asian-defaults.py
"""

from __future__ import annotations

import argparse
import base64
from pathlib import Path

from fontTools.ttLib import TTCollection, TTFont

DFONTS = Path("/Applications/Microsoft PowerPoint.app/Contents/Resources/DFonts")
OUTPUT = Path("packages/pptx/src/east-asian-default-coverage.ts")
# Repertoire lookup domain, including the language-dependent punctuation and
# symbol slots of issue #1653. This is a coverage superset, NOT a slot classifier:
# font-slot-compatibility.ts decides which of these characters actually uses ea.
RANGES = (
    (0x00A7, 0x00A8), (0x00B0, 0x00B1), (0x00B4, 0x00B4),
    (0x00D7, 0x00D7), (0x00F7, 0x00F7), (0x1100, 0x11FF),
    (0x2018, 0x201F), (0x2047, 0x2049), (0x2460, 0x27BF),
    (0x3000, 0x9FFF), (0xAC00, 0xD7A3), (0xF900, 0xFAFF),
    (0xFE30, 0xFE4F), (0xFF00, 0xFFEF),
)


def cmap(path: Path, index: int) -> set[int]:
    font = TTCollection(path).fonts[index] if path.suffix.lower() == ".ttc" else TTFont(path)
    return set(font.getBestCmap())


def slot_code_points() -> list[int]:
    return [cp for lo, hi in RANGES for cp in range(lo, hi + 1)]


def ranges(covered: set[int]) -> list[list[int]]:
    out: list[list[int]] = []
    for cp in sorted(c for c in covered if any(lo <= c <= hi for lo, hi in RANGES)):
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dfonts", type=Path, default=DFONTS)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    mincho = cmap(args.dfonts / "msmincho.ttc", 0)
    gothic = cmap(args.dfonts / "msgothic.ttc", 0)
    slot = slot_code_points()
    if {cp for cp in slot if cp in mincho} != {cp for cp in slot if cp in gothic}:
        raise SystemExit("MS Mincho and MS Gothic repertoires differ; store both")
    bits = bytearray((len(slot) + 7) // 8)
    for i, cp in enumerate(slot):
        if cp in mincho:
            bits[i >> 3] |= 1 << (i & 7)
    pmingliu = ranges(cmap(args.dfonts / "mingliu.ttc", 1))
    jhenghei = ranges(cmap(args.dfonts / "MSJH.ttf", 0))
    fmt = lambda rs: "[" + ", ".join(f"[0x{lo:04X}, 0x{hi:04X}]" for lo, hi in rs) + "]"
    text = f"""// Generated by scripts/generate-pptx-east-asian-defaults.py from the fonts
// bundled with Microsoft PowerPoint for Mac. Do not edit.
//
// Character repertoires (no outlines or metrics) of PowerPoint's first two
// application-default East Asian tiers over the renderer's East Asian slot
// code points ({", ".join(f"U+{lo:04X}-{hi:04X}" for lo, hi in RANGES)}).

/** East Asian slot ranges the bitmap indexes, in order. */
export const EAST_ASIAN_SLOT_RANGES: readonly (readonly [number, number])[] = {fmt(RANGES)};

/** MS Mincho / MS Gothic (one shared repertoire): bit i = i-th slot code point. */
export const MS_MINCHO_GOTHIC_BITMAP_BASE64 =
  '{base64.b64encode(bytes(bits)).decode()}';

/** PMingLiU repertoire within the slot ranges. */
export const PMINGLIU_RANGES: readonly (readonly [number, number])[] = {fmt(pmingliu)};

/** Microsoft JhengHei repertoire within the slot ranges. */
export const MICROSOFT_JHENGHEI_RANGES: readonly (readonly [number, number])[] = {fmt(jhenghei)};
"""
    args.output.write_text(text)
    print(f"wrote {args.output} ({len(bits)} bitmap bytes, {len(pmingliu)} + {len(jhenghei)} ranges)")


if __name__ == "__main__":
    main()
