//! Bounded single-level counter-instance probes generated by
//! `scripts/legacy-doc-counter-probes.py` and observed in native Word for Mac
//! 16.112.3. These cases do not establish behavior for general multilevel lists.

use super::NumberingMap;
use std::collections::HashMap;

const W: &str = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";

fn map(abstracts: &str, instances: &str) -> NumberingMap {
    NumberingMap::parse(
        &format!(r#"<w:numbering xmlns:w="{W}">{abstracts}{instances}</w:numbering>"#),
        &HashMap::new(),
    )
}

fn decimal_abstract(id: u32) -> String {
    format!(
        r#"<w:abstractNum w:abstractNumId="{id}">
              <w:multiLevelType w:val="singleLevel"/>
              <w:lvl w:ilvl="0">
                <w:start w:val="1"/>
                <w:numFmt w:val="decimal"/>
                <w:lvlText w:val="%1."/>
              </w:lvl>
            </w:abstractNum>"#
    )
}

fn instance(num_id: u32, abstract_id: u32, override_xml: &str) -> String {
    format!(
        r#"<w:num w:numId="{num_id}">
              <w:abstractNumId w:val="{abstract_id}"/>
              {override_xml}
            </w:num>"#
    )
}

fn counters(mut map: NumberingMap, sequence: &[u32]) -> Vec<u32> {
    sequence
        .iter()
        .map(|num_id| map.advance(*num_id, 0))
        .collect()
}

fn full_level(start: u32, marker_properties: &str) -> String {
    format!(
        r#"<w:lvlOverride w:ilvl="0">
              <w:lvl w:ilvl="0">
                <w:start w:val="{start}"/>
                <w:numFmt w:val="decimal"/>
                <w:lvlText w:val="%1."/>
                {marker_properties}
              </w:lvl>
            </w:lvlOverride>"#
    )
}

/// Bounded compatibility evidence from native Word: aliases of one abstract
/// numbering definition advance one shared counter. The cases intentionally
/// vary alias order and level formatting; they do not claim a normative rule.
#[test]
fn native_word_shared_abstract_alias_probes() {
    let abstract_xml = decimal_abstract(10);
    let bare_instances = format!("{}{}", instance(1, 10, ""), instance(2, 10, ""));
    let identical_level_instances = format!(
        "{}{}",
        instance(1, 10, ""),
        instance(2, 10, &full_level(1, ""))
    );
    let bold_level_instances = format!(
        "{}{}",
        instance(1, 10, ""),
        instance(2, 10, &full_level(1, "<w:rPr><w:b/></w:rPr>"))
    );
    let level_start_instances = format!(
        "{}{}",
        instance(1, 10, ""),
        instance(2, 10, &full_level(7, ""))
    );

    let cases: &[(&str, &[u32], &str)] = &[
        ("one instance", &[1, 1, 1, 1], &bare_instances),
        ("alternating bare aliases", &[1, 2, 1, 2], &bare_instances),
        ("grouped bare aliases", &[1, 1, 2, 2], &bare_instances),
        (
            "alias with identical full level",
            &[1, 2, 1, 2],
            &identical_level_instances,
        ),
        (
            "alias with marker formatting",
            &[1, 2, 1, 2],
            &bold_level_instances,
        ),
        (
            "alias with level start but no startOverride",
            &[1, 2, 1, 2],
            &level_start_instances,
        ),
        (
            "repeat alternating bare aliases",
            &[1, 2, 1, 2],
            &bare_instances,
        ),
    ];

    for (name, sequence, instances) in cases {
        assert_eq!(
            counters(map(&abstract_xml, instances), sequence),
            [1, 2, 3, 4],
            "{name}"
        );
    }
}

/// Native Word treats startOverride as an explicit restart even when the two
/// concrete numbering instances alias the same abstract definition.
#[test]
fn native_word_start_override_restarts_shared_abstract_probe() {
    let abstracts = decimal_abstract(10);
    let instances = format!(
        "{}{}",
        instance(1, 10, ""),
        instance(
            2,
            10,
            r#"<w:lvlOverride w:ilvl="0">
                  <w:startOverride w:val="7"/>
                </w:lvlOverride>"#,
        )
    );

    assert_eq!(
        counters(map(&abstracts, &instances), &[1, 2, 1, 2]),
        [1, 7, 8, 9]
    );
}

/// Native Word keeps counters separate for distinct abstract definitions even
/// when their level XML is otherwise equivalent.
#[test]
fn native_word_equivalent_distinct_abstracts_remain_separate_probe() {
    let abstracts = format!("{}{}", decimal_abstract(10), decimal_abstract(11));
    let instances = format!("{}{}", instance(1, 10, ""), instance(2, 11, ""));

    assert_eq!(
        counters(map(&abstracts, &instances), &[1, 2, 1, 2]),
        [1, 1, 2, 2]
    );
}
