// Generated by scripts/check-public-api.mjs.
// This file records every local declaration reachable from the XLSX public entry.
// Do not edit by hand.

// --- file: xlsx.d.ts ---
export interface ArrowEnd {
    type: string;
    w: string;
    len: string;
}
export function autoResize(render: (width: number, height: number) => void | Promise<void>, element: Element, opts?: AutoResizeOptions): () => void;
export interface AutoResizeOptions {
    pauseWhenHidden?: boolean;
}
export interface Border {
    left: BorderEdge | null;
    right: BorderEdge | null;
    top: BorderEdge | null;
    bottom: BorderEdge | null;
    diagonalUp?: BorderEdge | null;
    diagonalDown?: BorderEdge | null;
    horizontal?: BorderEdge | null;
    vertical?: BorderEdge | null;
}
export interface BorderEdge {
    style: string;
    color: string | null;
}
type CanvasViewerRenderMode = 'main' | 'worker';
export interface Cell {
    col: number;
    row: number;
    value: CellValue;
    styleIndex?: number;
    formula?: string;
    showPhonetic?: boolean;
}
export interface CellAddress {
    row: number;
    col: number;
}
export interface CellFill {
    patternType: string;
    fgColor: string | null;
    bgColor: string | null;
    gradient?: GradientFillSpec | null;
}
export interface CellFont {
    bold: boolean;
    italic: boolean;
    underline: boolean;
    strike: boolean;
    size: number;
    color: string | null;
    name: string | null;
    underlineStyle?: string;
    vertAlign?: 'superscript' | 'subscript';
}
export type CellValue = {
    type: 'empty';
} | {
    type: 'text';
    text: string;
    runs?: Run[];
    phoneticRuns?: PhoneticRun[];
    phoneticPr?: PhoneticProperties;
} | {
    type: 'number';
    number: number;
} | {
    type: 'bool';
    bool: boolean;
} | {
    type: 'error';
    error: string;
} | {
    type: 'shared';
    si: number;
};
export interface CellXf {
    fontId: number;
    fillId: number;
    borderId: number;
    numFmtId: number;
    alignH: string | null;
    alignV: string | null;
    wrapText: boolean;
    indent?: number;
    textRotation?: number;
    shrinkToFit?: boolean;
    readingOrder?: number;
}
export interface CfIcon {
    iconSet: string;
    iconId: number;
}
export type CfRule = {
    type: 'cellIs';
    operator: string;
    formulas: string[];
    dxfId: number | null;
    priority: number;
} | {
    type: 'expression';
    formula: string;
    dxfId: number | null;
    priority: number;
    stopIfTrue: boolean;
} | {
    type: 'colorScale';
    stops: CfStop[];
    priority: number;
} | {
    type: 'dataBar';
    color: string;
    min: CfValue;
    max: CfValue;
    priority: number;
    gradient: boolean;
} | {
    type: 'top10';
    top: boolean;
    percent: boolean;
    rank: number;
    dxfId: number | null;
    priority: number;
} | {
    type: 'aboveAverage';
    aboveAverage: boolean;
    equalAverage?: boolean;
    stdDev?: number;
    dxfId: number | null;
    priority: number;
} | {
    type: 'iconSet';
    iconSet: string;
    cfvos: CfValue[];
    reverse: boolean;
    priority: number;
    customIcons?: CfIcon[];
} | {
    type: 'other';
    kind: string;
    priority: number;
};
export interface CfStop {
    kind: string;
    value: string | null;
    color: string;
}
export interface CfValue {
    kind: string;
    value: string | null;
}
export interface ChartAnchor {
    zOrder?: number;
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    chart: ChartModel;
}
export interface ChartAreaGroupDecorations {
    groupIndex: number;
    dropLines?: ChartDecorationLineStyle | null;
}
export interface ChartBarGroupDecorations {
    groupIndex: number;
    seriesLines?: ChartDecorationLineStyle[] | null;
}
export interface ChartDataLabelOverride {
    idx: number;
    text: string;
    richRuns?: ChartTextRun[];
    position?: string;
    fontColor?: string;
    fontPaintAuthored?: boolean;
    fontHidden?: boolean;
    fontSizeHpt?: number;
    fontFace?: string;
    fontBold?: boolean;
    fontItalic?: boolean;
    fontLanguage?: string;
    fontBaseline?: number;
    textRotation?: number;
    textWrap?: string;
    textVerticalAnchor?: string;
    textVerticalMode?: string;
    textLInsEmu?: number;
    textTInsEmu?: number;
    textRInsEmu?: number;
    textBInsEmu?: number;
    textBodyAuthored?: boolean;
    textAlign?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string;
    formatCode?: string;
    separator?: string;
    manualLayout?: ChartManualLayout;
    labelBox?: ChartLabelBox;
    showVal?: boolean;
    showCatName?: boolean;
    showSerName?: boolean;
    showPercent?: boolean;
    showBubbleSize?: boolean;
    showLegendKey?: boolean;
    deleted?: boolean;
}
export interface ChartDataPointOverride {
    idx: number;
    color?: string;
    fillHidden?: boolean;
    chartexStyle?: ChartExElementStyle | null;
    lineColor?: string;
    lineWidthEmu?: number;
    lineDash?: string;
    lineHidden?: boolean;
    markerSymbol?: string;
    markerSize?: number;
    markerFill?: string;
    markerFillPaint?: Fill | null;
    markerFillPaintAuthored?: boolean | null;
    markerLine?: string;
    markerLineWidthEmu?: number;
    bubble3D?: boolean | null;
    explosion?: number;
}
export interface ChartDataTable {
    showHorizontalBorder: boolean;
    showVerticalBorder: boolean;
    showOutline: boolean;
    showKeys: boolean;
    fontSizeHpt?: number | null;
    fontFace?: string | null;
    fontColor?: string | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    /** Resolved solid compatibility projection of `<c:dTable><c:spPr>`. */
    fillColor?: string | null;
    /** Direct DrawingML fill recipe. Preserved even where Office's application-
     * defined data-table paint extent has not been established for that recipe. */
    fill?: SolidFill | GradientFill | PatternFill | null;
    /** Explicit `<a:noFill>` on the data-table shape properties. */
    fillHidden?: boolean | null;
    /** True when `spPr` authored any DrawingML fill child, including one whose
     * paint recipe this implementation cannot resolve. */
    fillPaintAuthored?: boolean | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden?: boolean | null;
}
export interface ChartDecorationLineStyle {
    color?: string | null;
    paintAuthored?: boolean | null;
    widthEmu?: number | null;
    dash?: string | null;
    cap?: string | null;
    join?: string | null;
    hidden?: boolean | null;
}
export interface ChartDisplayUnits {
    divisor: number;
    builtInUnit?: string | null;
    label?: ChartDisplayUnitsLabel | null;
}
export interface ChartDisplayUnitsLabel {
    text?: string | null;
    manualLayout?: ChartManualLayout | null;
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    fontColor?: string | null;
    fontFace?: string | null;
    rotation?: number | null;
    boxStyle?: ChartLabelBox | null;
}
export interface ChartErrBars {
    dir: string;
    barType: string;
    plus: (number | null)[];
    minus: (number | null)[];
    noEndCap: boolean;
    color?: string;
    lineWidthEmu?: number;
    dash?: string;
    hidden?: boolean;
}
export interface ChartexBoxSeries {
    name: string;
    chartexFormatIdx?: number | null;
    color?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    chartexStyle?: ChartExElementStyle | null;
    valuesByCategory: number[][];
    meanMarker: boolean;
    meanLine: boolean;
    showOutliers: boolean;
    showNonoutliers: boolean;
    quartileMethod: string;
}
export interface ChartexBoxWhisker {
    oneBoxPerSeries?: boolean;
    categories: string[];
    series: ChartexBoxSeries[];
}
export interface ChartExElementStyle {
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    fontColor?: string | null;
    fontPaintAuthored?: boolean | null;
    fontHidden?: boolean | null;
    fontFace?: string | null;
    fontLanguage?: string | null;
    fontBaseline?: number | null;
    textRotation?: number | null;
    textWrap?: string | null;
    textVerticalAnchor?: string | null;
    textVerticalMode?: string | null;
    textLInsEmu?: number | null;
    textTInsEmu?: number | null;
    textRInsEmu?: number | null;
    textBInsEmu?: number | null;
    textBodyAuthored?: boolean | null;
    fillPaints?: Array<Fill | null> | null;
    fillColors?: Array<string | null> | null;
    fillHidden?: boolean | null;
    fillPaintAuthored?: boolean | null;
    fillNoStyle?: boolean | null;
    lineColors?: Array<string | null> | null;
    linePaints?: Array<SolidFill | GradientFill | PatternFill | null> | null;
    linePaintAuthored?: boolean | null;
    lineWidthEmu?: number | null;
    lineHidden?: boolean | null;
    lineNoStyle?: boolean | null;
    lineDash?: string | null;
    lineDashAuthored?: boolean | null;
    lineCustomDash?: ChartLineDashSegment[] | null;
    lineCap?: string | null;
    lineJoin?: string | null;
    lineCompound?: string | null;
    fillColorIndex?: number | null;
    lineColorIndex?: number | null;
}
export interface ChartexGeography {
    projectionType?: 'mercator' | 'miller' | 'robinson' | 'albers' | string | null;
    viewedRegionType?: string | null;
    cultureLanguage?: string | null;
    cultureRegion?: string | null;
    attribution?: string | null;
    cacheProvider?: string | null;
    cachePresent: boolean;
}
export interface ChartexHistogramBinning {
    binSize?: number | null;
    binCount?: number | null;
    intervalClosed?: 'l' | 'r' | null;
    underflow?: number | null;
    overflow?: number | null;
}
export interface ChartexRegionMap {
    rows: ChartexRegionMapRow[];
    regionLabelLayout?: 'none' | 'bestFitOnly' | 'showAll' | null;
    geography?: ChartexGeography | null;
    colors?: ChartexRegionMapColors | null;
}
export interface ChartexRegionMapColors {
    stopCount?: 2 | 3 | null;
    minColor?: string | null;
    midColor?: string | null;
    maxColor?: string | null;
    minPosition?: ChartexValueColorStop | null;
    midPosition?: ChartexValueColorStop | null;
    maxPosition?: ChartexValueColorStop | null;
}
export interface ChartexRegionMapRow {
    label: string;
    entityId?: string | null;
    value?: number | null;
}
export interface ChartexSunburst {
    rows: ChartexSunburstRow[];
}
export interface ChartexSunburstRow {
    path: string[];
    size: number;
}
export interface ChartexTreemap {
    rows: ChartexSunburstRow[];
    parentLabelLayout?: string | null;
}
export interface ChartexValueColorStop {
    kind: 'extremeValue' | 'number' | 'percent' | string;
    value?: number | null;
}
export interface ChartLabelBox {
    fill?: string;
    fillPaint?: SolidFill | GradientFill | PatternFill | null;
    fillHidden?: boolean | null;
    fillPaintAuthored?: boolean | null;
    borderColor?: string;
    borderFill?: SolidFill | GradientFill | PatternFill | null;
    borderWidthEmu?: number;
    borderHidden?: boolean | null;
    borderPaintAuthored?: boolean | null;
    borderDash?: string | null;
    borderDashAuthored?: boolean | null;
    borderCustomDash?: ChartLineDashSegment[] | null;
    borderCap?: string | null;
    borderJoin?: string | null;
    borderCompound?: string | null;
}
export interface ChartLegendEntryOverride {
    idx: number;
    deleted?: boolean | null;
    fontFace?: string | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
}
export type ChartLineDashSegment = DrawingMLCustomDashSegment;
export interface ChartLineGroupDecorations {
    groupIndex: number;
    dropLines?: ChartDecorationLineStyle | null;
    hiLowLines?: ChartDecorationLineStyle | null;
    upDownBars?: ChartStockUpDownBarStyle | null;
}
export interface ChartManualLayout {
    xMode?: string;
    yMode?: string;
    wMode?: string;
    hMode?: string;
    layoutTarget?: string;
    x: number;
    y: number;
    w?: number;
    h?: number;
}
export interface ChartModel {
    chartType: ChartType;
    title: string | null;
    titleRichRuns?: ChartTextRun[] | null;
    titlePresent?: boolean;
    categories: string[];
    categorySourceHidden?: boolean[] | null;
    categoryLevels?: string[][] | null;
    series: ChartSeries[];
    plotGroups?: ChartPlotGroup[] | null;
    chartTextBoxes?: ChartTextBox[] | null;
    varyColors?: boolean | null;
    showDataLabels: boolean;
    valMin: number | null;
    valMax: number | null;
    catAxisTitle: string | null;
    valAxisTitle: string | null;
    catAxisHidden: boolean;
    valAxisHidden: boolean;
    catAxisLineHidden: boolean;
    valAxisLineHidden: boolean;
    plotAreaBg: string | null;
    plotAreaFill?: Fill | null;
    plotAreaFillHidden?: boolean | null;
    plotAreaFillPaintAuthored?: boolean | null;
    plotAreaFillAutomatic?: boolean | null;
    plotAreaLineColor?: string | null;
    plotAreaLineFill?: SolidFill | GradientFill | PatternFill | null;
    plotAreaLineWidthEmu?: number | null;
    plotAreaLineDash?: string | null;
    plotAreaLineDashAuthored?: boolean | null;
    plotAreaLineCustomDash?: ChartLineDashSegment[] | null;
    plotAreaLineCap?: string | null;
    plotAreaLineJoin?: string | null;
    plotAreaLineCompound?: string | null;
    plotAreaLineHidden?: boolean | null;
    plotAreaLinePaintAuthored?: boolean | null;
    chartBg: string | null;
    chartFill?: Fill | null;
    chartFillHidden?: boolean | null;
    chartFillPaintAuthored?: boolean | null;
    roundedCorners?: boolean | null;
    plotVisibleOnly?: boolean | null;
    showLegend: boolean;
    dataTable?: ChartDataTable | null;
    legendPos: 'r' | 'l' | 't' | 'b' | 'tr' | null;
    legendOverlay?: boolean | null;
    legendEntries?: ChartLegendEntryOverride[] | null;
    catAxisCrossBetween: 'between' | 'midCat' | string;
    valAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    catAxisMajorTickMark: 'cross' | 'out' | 'in' | 'none' | string;
    valAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    catAxisMinorTickMark?: 'cross' | 'out' | 'in' | 'none' | string | null;
    titleFontSizeHpt: number | null;
    titleFontColor: string | null;
    titleFontFace: string | null;
    catAxisFontSizeHpt: number | null;
    valAxisFontSizeHpt: number | null;
    catAxisFontColor?: string | null;
    valAxisFontColor?: string | null;
    dataLabelFontSizeHpt: number | null;
    dataLabelFontBold?: boolean | null;
    subtotalIndices: number[];
    legendManualLayout?: LegendManualLayout | null;
    valAxisFormatCode?: string | null;
    valAxisDisplayUnits?: ChartDisplayUnits | null;
    catAxisDisplayUnits?: ChartDisplayUnits | null;
    barGapWidth?: number | null;
    barOverlap?: number | null;
    dataLabelPosition?: string | null;
    dataLabelFontColor?: string | null;
    dataLabelFormatCode?: string | null;
    titleFontBold?: boolean | null;
    catAxisFontBold?: boolean | null;
    catAxisFontItalic?: boolean | null;
    valAxisFontBold?: boolean | null;
    valAxisFontItalic?: boolean | null;
    catAxisTitleFontSizeHpt?: number | null;
    catAxisTitleFontBold?: boolean | null;
    catAxisTitleFontItalic?: boolean | null;
    catAxisTitleFontColor?: string | null;
    catAxisTitleRotation?: number | null;
    catAxisTitleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    catAxisTitleManualLayout?: ChartManualLayout | null;
    catAxisTitleTextVerticalInsetEmu?: number | null;
    valAxisTitleFontSizeHpt?: number | null;
    valAxisTitleFontBold?: boolean | null;
    valAxisTitleFontItalic?: boolean | null;
    valAxisTitleFontColor?: string | null;
    valAxisTitleRotation?: number | null;
    valAxisTitleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    valAxisTitleManualLayout?: ChartManualLayout | null;
    valAxisTitleTextVerticalInsetEmu?: number | null;
    catAxisFontFace?: string | null;
    valAxisFontFace?: string | null;
    catAxisTitleFontFace?: string | null;
    valAxisTitleFontFace?: string | null;
    dataLabelFontFace?: string | null;
    legendFontFace?: string | null;
    legendFontColor?: string | null;
    legendFontSizeHpt?: number | null;
    legendFontBold?: boolean | null;
    legendFillColor?: string | null;
    legendFill?: Fill | null;
    legendFillHidden?: boolean | null;
    legendFillPaintAuthored?: boolean | null;
    legendLineColor?: string | null;
    legendLineFill?: SolidFill | GradientFill | PatternFill | null;
    legendLineWidthEmu?: number | null;
    legendLineDash?: string | null;
    legendLineDashAuthored?: boolean | null;
    legendLineCustomDash?: ChartLineDashSegment[] | null;
    legendLineCap?: string | null;
    legendLineJoin?: string | null;
    legendLineCompound?: string | null;
    legendLineHidden?: boolean | null;
    legendLinePaintAuthored?: boolean | null;
    themeMajorFontLatin?: string | null;
    themeMinorFontLatin?: string | null;
    chartBorderColor?: string | null;
    chartBorderLineFill?: SolidFill | GradientFill | PatternFill | null;
    chartBorderWidthEmu?: number | null;
    chartBorderDash?: string | null;
    chartBorderDashAuthored?: boolean | null;
    chartBorderCustomDash?: ChartLineDashSegment[] | null;
    chartBorderCap?: string | null;
    chartBorderJoin?: string | null;
    chartBorderCompound?: string | null;
    chartBorderHidden?: boolean | null;
    chartBorderPaintAuthored?: boolean | null;
    catAxisCrosses?: string | null;
    catAxisCrossesAt?: number | null;
    valAxisCrosses?: string | null;
    valAxisCrossesAt?: number | null;
    catAxisLineColor?: string | null;
    catAxisLineWidthEmu?: number | null;
    catAxisLineDash?: string | null;
    /** A direct `<c:catAx><c:spPr><a:ln>` paint was authored. */
    catAxisLinePaintAuthored?: boolean | null;
    valAxisLineColor?: string | null;
    valAxisLineWidthEmu?: number | null;
    valAxisLineDash?: string | null;
    /** A direct `<c:valAx><c:spPr><a:ln>` paint was authored. */
    valAxisLinePaintAuthored?: boolean | null;
    catAxisFormatCode?: string | null;
    catAxisMin?: number | null;
    catAxisMax?: number | null;
    titleManualLayout?: ChartManualLayout | null;
    plotAreaManualLayout?: ChartManualLayout | null;
    scatterStyle?: string | null;
    bubbleScale?: number | null;
    bubbleSizeRepresents?: 'area' | 'w' | null;
    showNegativeBubbles?: boolean | null;
    radarStyle?: string | null;
    secondaryValAxis?: SecondaryValueAxis | null;
    secondaryCatAxis?: SecondaryValueAxis | null;
    date1904?: boolean;
    holeSize?: number | null;
    firstSliceAngle?: number | null;
    dispBlanksAs?: string | null;
    showDataLabelsOverMax?: boolean | null;
    valAxisMajorGridlines?: boolean | null;
    catAxisMajorGridlines?: boolean | null;
    valAxisGridlineColor?: string | null;
    valAxisGridlineWidthEmu?: number | null;
    valAxisGridlineDash?: string | null;
    catAxisGridlineColor?: string | null;
    catAxisGridlineWidthEmu?: number | null;
    catAxisGridlineDash?: string | null;
    valAxisMinorGridlines?: boolean | null;
    valAxisMinorGridlineColor?: string | null;
    valAxisMinorGridlineWidthEmu?: number | null;
    valAxisMinorGridlineDash?: string | null;
    catAxisMinorGridlines?: boolean | null;
    catAxisMinorGridlineColor?: string | null;
    catAxisMinorGridlineWidthEmu?: number | null;
    catAxisMinorGridlineDash?: string | null;
    valAxisMajorUnit?: number | null;
    valAxisMinorUnit?: number | null;
    catAxisMajorUnit?: number | null;
    catAxisMinorUnit?: number | null;
    catAxisIsDate?: boolean | null;
    catAxisBaseTimeUnit?: 'days' | 'months' | 'years' | string | null;
    catAxisMajorTimeUnit?: 'days' | 'months' | 'years' | string | null;
    catAxisMinorTimeUnit?: 'days' | 'months' | 'years' | string | null;
    catAxisNoMultiLevelLabels?: boolean | null;
    valAxisLogBase?: number | null;
    catAxisLogBase?: number | null;
    valAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisOrientation?: 'minMax' | 'maxMin' | string | null;
    catAxisTickLabelPos?: string | null;
    catAxisTickLabelSkip?: number | null;
    catAxisTickMarkSkip?: number | null;
    catAxisLabelAlignment?: 'l' | 'ctr' | 'r' | string | null;
    catAxisLabelOffsetPercent?: number | null;
    valAxisTickLabelPos?: string | null;
    catAxisLabelRotation?: number | null;
    lineGroupDecorations?: ChartLineGroupDecorations[] | null;
    areaGroupDecorations?: ChartAreaGroupDecorations[] | null;
    barGroupDecorations?: ChartBarGroupDecorations[] | null;
    stockDropLines?: ChartDecorationLineStyle | null;
    stockHiLowLineStyle?: ChartDecorationLineStyle | null;
    stockHiLowLines?: boolean | null;
    stockHiLowLineColor?: string | null;
    stockUpDownBars?: boolean | null;
    stockUpDownBarStyle?: ChartStockUpDownBarStyle | null;
    stockAutomaticStyle?: {
        lineColor: string;
        lineWidthEmu: number;
        upFillColor: string;
        downFillColor: string;
    } | null;
    surfaceWireframe?: boolean | null;
    surfaceBandFormats?: ChartSurfaceBandFormat[] | null;
    legacyChartStyle?: number | null;
    themeAccentColors?: string[] | null;
    ofPie?: ChartOfPie | null;
    threeD?: ChartThreeD | null;
    chartexBox?: ChartexBoxWhisker | null;
    chartexSunburst?: ChartexSunburst | null;
    chartexTreemap?: ChartexTreemap | null;
    chartexRegionMap?: ChartexRegionMap | null;
    chartexHistogramBinning?: ChartexHistogramBinning | null;
    chartexAccents?: string[] | null;
    chartexColorPalette?: Array<string | null> | null;
    chartexColorStyleMethod?: string | null;
    chartStyleRoles?: Partial<Record<ChartStyleRole, ChartExElementStyle>> | null;
    chartStyleColorPalette?: Array<string | null> | null;
    chartStyleColorMethod?: string | null;
    chartStyleMarkerSizePt?: number | null;
    chartStyleMarkerSymbol?: string | null;
    chartexDataPointStyle?: ChartExElementStyle | null;
    chartexDataPointLineStyle?: ChartExElementStyle | null;
    chartexSeriesLineStyle?: ChartExElementStyle | null;
    chartexDataPointMarkerStyle?: ChartExElementStyle | null;
    chartexMarkerSizePt?: number | null;
    chartexMarkerSymbol?: string | null;
    chartexConnectorLines?: boolean | null;
}
export interface ChartOfPie {
    type: 'pie' | 'bar';
    splitType: 'auto' | 'cust' | 'percent' | 'pos' | 'val';
    splitTypeAuthored?: boolean | null;
    splitPos?: number | null;
    splitPosAuthored?: boolean | null;
    customSplitIndices?: number[] | null;
    secondPieSizePercent: number;
    gapWidthPercent: number;
    seriesLines: boolean;
}
export interface ChartRect {
    x: number;
    y: number;
    w: number;
    h: number;
}
export interface ChartExRenderer {
    render(ctx: CanvasRenderingContext2D, chart: ChartModel, rect: ChartRect, ptToPx: number, shapeRotationDeg?: number): boolean;
}
export interface ChartRegionMapRenderer {
    render(ctx: CanvasRenderingContext2D, chart: ChartModel, rect: ChartRect, ptToPx: number, shapeRotationDeg?: number): boolean;
}
export interface ChartSeries {
    name: string;
    chartexFormatIdx?: number | null;
    color: string | null;
    fillPattern?: PatternFill | null;
    invertIfNegative?: boolean | null;
    automaticNegativeStyle?: boolean | null;
    invertedFill?: SolidFill | GradientFill | PatternFill | null;
    invertedFillHidden?: boolean | null;
    invertedFillAuthored?: boolean | null;
    invertedLineColor?: string | null;
    invertedLineWidthEmu?: number | null;
    invertedLineHidden?: boolean | null;
    invertedLineAuthored?: boolean | null;
    chartexStyle?: ChartExElementStyle | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    threeDShape?: 'box' | 'cylinder' | 'cone' | 'coneToMax' | 'pyramid' | 'pyramidToMax' | string | null;
    values: (number | null)[];
    sourceHidden?: boolean[] | null;
    dataPointColors?: (string | null)[] | null;
    explosion?: number | null;
    dataLabelColors?: (string | null)[] | null;
    labelColor?: string | null;
    seriesType?: string | null;
    lineGroupIndex?: number | null;
    areaGroupIndex?: number | null;
    barGroupIndex?: number | null;
    barGroupDirection?: 'bar' | 'col' | string | null;
    barGroupGrouping?: 'standard' | 'clustered' | 'stacked' | 'percentStacked' | string | null;
    barGroupGapWidth?: number | null;
    barGroupOverlap?: number | null;
    useSecondaryAxis?: boolean | null;
    categories?: string[] | null;
    /** Bubble-only provenance for a string-backed `<c:xVal>` source. Excel
     * exposes such a lone bubble series as one legend entry per point while a
     * numeric X source keeps the ordinary one-entry-per-series legend. */
    bubbleXSourceIsString?: boolean | null;
    showMarker?: boolean | null;
    valFormatCode?: string | null;
    catFormatCode?: string | null;
    catFormatBuiltinId?: number | null;
    catFormatCodes?: (string | null)[] | null;
    markerSymbol?: string | null;
    /** Host-resolved automatic scatter marker when no `<c:marker>` symbol is authored. */
    automaticMarkerSymbol?: string | null;
    markerSize?: number | null;
    markerFill?: string | null;
    markerFillPaint?: Fill | null;
    markerFillPaintAuthored?: boolean | null;
    markerLine?: string | null;
    markerLineWidthEmu?: number | null;
    dataPointOverrides?: ChartDataPointOverride[] | null;
    dataLabelOverrides?: ChartDataLabelOverride[] | null;
    seriesDataLabels?: ChartSeriesDataLabels | null;
    errBars?: ChartErrBars[] | null;
    bubbleSizes?: (number | null)[] | null;
    bubble3DGroupDefault?: boolean | null;
    bubble3D?: boolean | null;
    smooth?: boolean | null;
    trendLines?: ChartTrendline[] | null;
    lineHidden?: boolean | null;
}
export interface ChartSeriesDataLabels {
    deleted?: boolean | null;
    showVal: boolean;
    showCatName: boolean;
    showSerName: boolean;
    showPercent: boolean;
    showBubbleSize?: boolean;
    showLegendKey?: boolean;
    position?: string;
    fontColor?: string;
    fontPaintAuthored?: boolean;
    fontHidden?: boolean;
    formatCode?: string;
    separator?: string;
    fontBold?: boolean;
    fontItalic?: boolean;
    fontLanguage?: string;
    fontBaseline?: number;
    fontSizeHpt?: number;
    fontFace?: string;
    textRotation?: number;
    textWrap?: string;
    textVerticalAnchor?: string;
    textVerticalMode?: string;
    textLInsEmu?: number;
    textTInsEmu?: number;
    textRInsEmu?: number;
    textBInsEmu?: number;
    textBodyAuthored?: boolean;
    textAlign?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string;
    labelBox?: ChartLabelBox;
    showLeaderLines?: boolean;
    leaderLineColor?: string;
    leaderLineWidthEmu?: number;
    leaderLineHidden?: boolean;
    leaderLineDash?: string;
}
export interface ChartStockBarPaint {
    fillColor?: string | null;
    fill?: SolidFill | GradientFill | PatternFill | null;
    fillPaintAuthored?: boolean | null;
    fillHidden?: boolean | null;
    lineColor?: string | null;
    linePaintAuthored?: boolean | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineCap?: string | null;
    lineJoin?: string | null;
    lineHidden?: boolean | null;
}
export interface ChartStockUpDownBarStyle {
    gapWidthPercent: number;
    up: ChartStockBarPaint;
    down: ChartStockBarPaint;
}
type ChartStyleRole = 'axisTitle' | 'categoryAxis' | 'chartArea' | 'dataLabel' | 'dataLabelCallout' | 'dataPoint' | 'dataPoint3D' | 'dataPointLine' | 'dataPointMarker' | 'dataPointWireframe' | 'dataTable' | 'downBar' | 'dropLine' | 'errorBar' | 'floor' | 'gridlineMajor' | 'gridlineMinor' | 'hiLoLine' | 'leaderLine' | 'legend' | 'plotArea' | 'plotArea3D' | 'seriesAxis' | 'seriesLine' | 'title' | 'trendline' | 'trendlineLabel' | 'upBar' | 'valueAxis' | 'wall';
export interface ChartSurfaceBandFormat {
    idx: number;
    style?: ChartExElementStyle | null;
    fill?: SolidFill | GradientFill | PatternFill | null;
    fillHidden?: boolean | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineHidden?: boolean | null;
}
export interface ChartTextBox {
    x: number;
    y: number;
    w: number;
    h: number;
    paragraphs: ChartTextParagraph[];
    verticalAnchor?: 't' | 'ctr' | 'b' | 'just' | 'dist' | string | null;
    wrap?: 'none' | 'square' | string | null;
    lIns?: number;
    tIns?: number;
    rIns?: number;
    bIns?: number;
}
export interface ChartTextParagraph {
    runs: ChartTextRun[];
    align?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string | null;
}
export interface ChartTextRun {
    text: string;
    fontSizeHpt?: number | null;
    bold?: boolean | null;
    italic?: boolean | null;
    color?: string | null;
    colorPaintAuthored?: boolean | null;
    colorHidden?: boolean | null;
    fontFace?: string | null;
    language?: string | null;
    baseline?: number | null;
    paragraphAlign?: 'l' | 'ctr' | 'r' | 'just' | 'dist' | string | null;
}
export interface ChartThreeD {
    view3DPresent?: boolean | null;
    rotationX?: number | null;
    rotationXAuthored?: boolean | null;
    rotationY?: number | null;
    rotationYAuthored?: boolean | null;
    heightPercent?: number | null;
    heightPercentAuthored?: boolean | null;
    depthPercent?: number | null;
    depthPercentAuthored?: boolean | null;
    perspective?: number | null;
    perspectiveAuthored?: boolean | null;
    rightAngleAxes?: boolean | null;
    rightAngleAxesAuthored?: boolean | null;
    gapDepthPercent?: number | null;
    gapDepthPercentAuthored?: boolean | null;
    shape?: string | null;
    barGrouping?: 'standard' | 'clustered' | 'stacked' | 'percentStacked' | string | null;
    seriesAxis?: ChartThreeDSeriesAxis | null;
    floor?: ChartThreeDSurface | null;
    sideWall?: ChartThreeDSurface | null;
    backWall?: ChartThreeDSurface | null;
}
export interface ChartThreeDPictureOptions {
    applyToFront?: boolean | null;
    applyToSides?: boolean | null;
    applyToEnd?: boolean | null;
    pictureFormat?: 'stretch' | 'stack' | 'stackScale' | string | null;
    /** Whether `<c:pictureFormat>` was authored, including an unsupported value. */
    pictureFormatAuthored?: boolean | null;
    pictureStackUnit?: number | null;
    /** Whether `<c:pictureStackUnit>` was authored, including an invalid value. */
    pictureStackUnitAuthored?: boolean | null;
}
export interface ChartThreeDRenderer {
    render(ctx: CanvasRenderingContext2D, chart: ChartModel, rect: ChartRect, ptToPx: number, shapeRotationDeg?: number): boolean;
}
export interface ChartThreeDSeriesAxis {
    title?: string | null;
    hidden: boolean;
    orientation?: 'minMax' | 'maxMin' | string | null;
    tickLabelPos?: string | null;
    tickLabelSkip?: number | null;
    tickMarkSkip?: number | null;
    majorTickMark: string;
    /** `<c:serAx><c:minorTickMark>`; omission means no minor tick marks. */
    minorTickMark?: string | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    fontBold?: boolean | null;
    fontItalic?: boolean | null;
    fontFace?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    /** A direct `<c:serAx><c:spPr><a:ln>` paint was authored. */
    linePaintAuthored?: boolean | null;
    lineHidden: boolean;
    titleFontSizeHpt?: number | null;
    titleFontBold?: boolean | null;
    titleFontItalic?: boolean | null;
    titleFontColor?: string | null;
    titleFontFace?: string | null;
    titleRotation?: number | null;
    titleVerticalMode?: ChartModel['catAxisTitleVerticalMode'];
    titleManualLayout?: ChartManualLayout | null;
}
export interface ChartThreeDSurface {
    style?: ChartExElementStyle | null;
    fillColor?: string | null;
    fillHidden?: boolean | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden?: boolean | null;
    thicknessPercent?: number | null;
    pictureOptions?: ChartThreeDPictureOptions | null;
}
export interface ChartTrendline {
    name?: string | null;
    trendlineType: string;
    order?: number | null;
    period?: number | null;
    forward?: number | null;
    backward?: number | null;
    intercept?: number | null;
    dispRSqr?: boolean | null;
    dispEq?: boolean | null;
    labelManualLayout?: ChartManualLayout | null;
    labelText?: string | null;
    labelRichRuns?: ChartTextRun[] | null;
    labelFormatCode?: string | null;
    labelFormatSourceLinked?: boolean | null;
    labelFontSizeHpt?: number | null;
    labelFontBold?: boolean | null;
    labelFontItalic?: boolean | null;
    labelFontColor?: string | null;
    labelFontPaintAuthored?: boolean | null;
    labelFontHidden?: boolean | null;
    labelFontFace?: string | null;
    labelFontLanguage?: string | null;
    labelFontBaseline?: number | null;
    labelTextRotation?: number | null;
    labelTextWrap?: string | null;
    labelTextVerticalAnchor?: string | null;
    labelTextVerticalMode?: string | null;
    labelTextLInsEmu?: number | null;
    labelTextTInsEmu?: number | null;
    labelTextRInsEmu?: number | null;
    labelTextBInsEmu?: number | null;
    labelTextBodyAuthored?: boolean | null;
    labelBox?: ChartLabelBox | null;
    labelTextAlign?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden?: boolean | null;
}
export type ChartType = 'line' | 'stackedLine' | 'stackedLinePct' | 'clusteredBar' | 'clusteredBarH' | 'stackedBar' | 'stackedBarH' | 'stackedBarPct' | 'stackedBarHPct' | 'area' | 'stackedArea' | 'stackedAreaPct' | 'pie' | 'doughnut' | 'scatter' | 'bubble' | 'radar' | 'waterfall' | 'stock' | 'surface' | 'surface3D' | 'boxWhisker' | 'sunburst' | 'treemap' | string;
export type ChartPlotGroupKind = 'area' | 'area3D' | 'line' | 'line3D' | 'stock' | 'radar' | 'scatter' | 'pie' | 'pie3D' | 'doughnut' | 'bar' | 'bar3D' | 'ofPie' | 'surface' | 'surface3D' | 'bubble';
export type ChartPlotGroupAxisSlot = 'primary' | 'secondary' | 'none' | 'unresolved';
export interface ChartPlotGroup {
    kind: ChartPlotGroupKind;
    seriesStart: number;
    seriesCount: number;
    categoryAxis: ChartPlotGroupAxisSlot;
    valueAxis: ChartPlotGroupAxisSlot;
    seriesAxis: ChartPlotGroupAxisSlot;
    axisIds?: string[] | null;
    grouping?: string | null;
    barDirection?: string | null;
    scatterStyle?: string | null;
    radarStyle?: string | null;
    gapWidth?: number | null;
    overlap?: number | null;
    bubbleScale?: number | null;
    bubbleSizeRepresents?: 'area' | 'w' | null;
    showNegativeBubbles?: boolean | null;
}
export interface ConditionalFormat {
    sqref: WorksheetCellRange[];
    rules: CfRule[];
}
export interface DataValidation {
    sqref: string;
    validationType?: string;
    operator?: string;
    formula1?: string;
    formula2?: string;
    allowBlank?: boolean;
    promptTitle?: string;
    prompt?: string;
    errorTitle?: string;
    errorMessage?: string;
}
export interface DefinedName {
    name: string;
    formula: string;
}
export interface DrawingMLCustomDashSegment {
    dash: number;
    space: number;
}
export interface Duotone {
    clr1: string;
    clr2: string;
}
interface Duotone__emitterCollision1 {
    clr1: string;
    clr2: string;
}
export interface Dxf {
    font: CellFont | null;
    fill: CellFill | null;
    border: Border | null;
    numFmt?: NumFmt | null;
}
type ExtensibleLiteral<Known extends string> = Known | (string & Record<never, never>);
type Fill = SolidFill | NoFill | GradientFill | PatternFill | ImageFill;
export interface FillRect {
    l?: number;
    t?: number;
    r?: number;
    b?: number;
}
export interface FindHighlightColors {
    match?: string;
    active?: string;
}
export interface FindMatch<Loc = unknown> {
    matchIndex: number;
    text: string;
    location: Loc;
}
export interface FindMatchesOptions {
    caseSensitive?: boolean;
}
export interface GradientFill {
    fillType: 'gradient';
    stops: GradientStop[];
    angle: number;
    gradType: string;
    scaled?: boolean;
    path?: 'shape' | 'circle' | 'rect' | string;
    fillToRect?: FillRect;
    tileRect?: FillRect;
    flip?: 'none' | 'x' | 'y' | 'xy' | string;
    rotWithShape?: boolean;
}
export interface GradientFillSpec {
    gradientType: string;
    degree: number;
    left: number;
    right: number;
    top: number;
    bottom: number;
    stops: {
        position: number;
        color: string;
    }[];
}
export interface GradientStop {
    position: number;
    color: string;
}
export type HiddenSheetMode = 'show' | 'skip' | 'dim';
export interface Hyperlink {
    col: number;
    row: number;
    url: string | null;
    location?: string | null;
    display?: string | null;
}
export type HyperlinkTarget = {
    kind: 'external';
    url: string;
} | {
    kind: 'internal';
    ref: string;
    slideIndex?: number;
};
export interface ImageAnchor {
    zOrder?: number;
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    editAs?: string;
    nativeExtCx: number;
    nativeExtCy: number;
    imagePath: string;
    mimeType: string;
    svgImagePath?: string;
    srcRect?: {
        l: number;
        t: number;
        r: number;
        b: number;
    };
    alpha?: number;
    duotone?: Duotone;
}
export interface ImageFill {
    fillType: 'image';
    imagePath: string;
    svgImagePath?: string;
    mimeType: string;
    dpi?: number;
    rotWithShape?: boolean;
    srcRect?: SrcRect;
    fillRect?: FillRect;
    stretch?: boolean;
    tile?: TileInfo;
    alpha?: number;
    duotone?: Duotone__emitterCollision1;
}
export function isOoxmlDecodedImageLimitError(error: unknown): error is OoxmlDecodedImageLimitError;
export interface LegendManualLayout {
    xMode?: string;
    yMode?: string;
    wMode?: string;
    hMode?: string;
    x: number;
    y: number;
    w?: number;
    h?: number;
}
export interface LoadOptions extends LoadOptions__emitterCollision1 {
    mode?: 'main' | 'worker';
}
interface LoadOptions__emitterCollision1 {
    useGoogleFonts?: boolean;
    password?: string;
    wasmUrl?: string | URL;
    maxZipEntryBytes?: number;
    resourceLimits?: OoxmlResourceLimits;
    debug?: boolean;
    onResourceMetrics?: (metrics: OoxmlResourceMetrics) => void;
    workerTimeoutMs?: number;
    math?: MathRenderer;
    threeD?: ChartThreeDRenderer;
    regionMap?: ChartRegionMapRenderer;
    chartEx?: ChartExRenderer;
}
export interface MathAccent {
    kind: 'accent';
    char: string;
    base: MathNode[];
}
export interface MathArray {
    kind: 'array';
    rows: MathNode[][][];
    align: 'eq' | 'center' | 'left';
}
export interface MathBar {
    kind: 'bar';
    pos: 'top' | 'bot';
    base: MathNode[];
}
export interface MathBorderBox {
    kind: 'borderBox';
    hideTop?: boolean;
    hideBot?: boolean;
    hideLeft?: boolean;
    hideRight?: boolean;
    strikeH?: boolean;
    strikeV?: boolean;
    strikeBltr?: boolean;
    strikeTlbr?: boolean;
    base: MathNode[];
}
export interface MathBox {
    kind: 'box';
    base: MathNode[];
}
export interface MathDelimiter {
    kind: 'delimiter';
    begChar: string;
    endChar: string;
    items: MathNode[][];
}
export interface MathFraction {
    kind: 'fraction';
    num: MathNode[];
    den: MathNode[];
    bar?: boolean;
}
export interface MathFunc {
    kind: 'func';
    name: MathNode[];
    arg: MathNode[];
}
export interface MathGroup {
    kind: 'group';
    items: MathNode[];
}
export interface MathGroupChr {
    kind: 'groupChr';
    char: string;
    pos: 'top' | 'bot';
    base: MathNode[];
}
export interface MathLimit {
    kind: 'limit';
    base: MathNode[];
    lower?: MathNode[];
    upper?: MathNode[];
}
export interface MathNary {
    kind: 'nary';
    op: string;
    limLoc?: string;
    sub?: MathNode[];
    sup?: MathNode[];
    body: MathNode[];
}
export type MathNode = MathRun | MathFraction | MathScript | MathNary | MathDelimiter | MathRadical | MathLimit | MathArray | MathGroupChr | MathBar | MathAccent | MathFunc | MathGroup | MathPhant | MathSPre | MathBox | MathBorderBox;
export interface MathPhant {
    kind: 'phant';
    show: boolean;
    zeroWid?: boolean;
    zeroAsc?: boolean;
    zeroDesc?: boolean;
    base: MathNode[];
}
export interface MathRadical {
    kind: 'radical';
    index?: MathNode[];
    radicand: MathNode[];
}
export interface MathRenderer {
    loadMathJax(): Promise<void>;
    mathMLToSvg(mathml: string): Promise<MathSvg>;
}
export interface MathRun {
    kind: 'run';
    text: string;
    style: MathStyle;
}
export interface MathScript {
    kind: 'sup' | 'sub' | 'subSup';
    base: MathNode[];
    sup?: MathNode[];
    sub?: MathNode[];
}
export interface MathSPre {
    kind: 'sPre';
    sub: MathNode[];
    sup: MathNode[];
    base: MathNode[];
}
export type MathStyle = 'roman' | 'italic' | 'bold' | 'boldItalic';
export interface MathSvg {
    svg: string;
    widthEm: number;
    ascentEm: number;
    descentEm: number;
}
export const MAX_SELECTION_AREAS = 128;
export const MAX_SELECTION_CONTEXT_CELLS = 10000;
export const MAX_SELECTION_CONTEXT_TEXT_CHARACTERS: number;
export interface MergeCell {
    top: number;
    left: number;
    bottom: number;
    right: number;
}
export interface NoFill {
    fillType: 'none';
}
export interface NumFmt {
    numFmtId: number;
    formatCode: string;
}
export class OoxmlDecodedImageLimitError extends RangeError {
    readonly metric: OoxmlDecodedImageLimitMetric;
    readonly limit: number;
    readonly observed: number;
    readonly code: 'ooxml-decoded-image-limit';
    constructor(metric: OoxmlDecodedImageLimitMetric, limit: number, observed: number);
}
export type OoxmlDecodedImageLimitMetric = 'image-pixels' | 'active-decoded-bytes';
export class OoxmlError extends Error {
    readonly code: OoxmlErrorCode;
    constructor(code: OoxmlErrorCode, message: string);
}
export type OoxmlErrorCode = 'encrypted' | 'invalid-password' | 'unsupported-encryption' | 'legacy-binary-format' | 'not-ooxml';
export type OoxmlErrorStage = 'container' | 'decompression' | 'parsing' | 'serialization' | 'layout' | 'rendering' | 'worker';
export type OoxmlFormat = 'docx' | 'xlsx' | 'pptx';
export type OoxmlResourceLimit = number | null;
export class OoxmlResourceLimitError extends Error {
    readonly code: 'ooxml-resource-limit';
    readonly details: OoxmlResourceLimitErrorDetails;
    constructor(message: string, details: OoxmlResourceLimitErrorDetails);
}
export interface OoxmlResourceLimitErrorDetails {
    readonly stage: OoxmlErrorStage;
    readonly violation: OoxmlResourceViolation;
}
export interface OoxmlResourceLimits {
    maxArchiveEntryBytes?: OoxmlResourceLimit;
    maxTotalInflatedBytes?: OoxmlResourceLimit;
    maxArchiveEntries?: OoxmlResourceLimit;
}
export type OoxmlResourceMetric = ExtensibleLiteral<'declared-inflated-bytes' | 'actual-inflated-bytes' | 'entry-count' | 'central-directory-bytes' | 'distinct-inflated-bytes' | 'bytes' | 'depth' | 'projected-bytes'>;
export interface OoxmlResourceMetrics {
    readonly schemaVersion: 1;
    readonly scope: 'load' | 'session';
    readonly format: OoxmlFormat;
    readonly mode: 'main' | 'worker' | 'node';
    readonly status: 'ok' | 'error';
    readonly sourceBytes?: number;
    readonly elapsedMs: number;
    readonly policy: Readonly<OoxmlResourcePolicySnapshot>;
    readonly usage?: OoxmlResourceUsageSnapshot;
    readonly checkpoints: readonly OoxmlResourceMetricsCheckpoint[];
    readonly outcome?: Readonly<Record<string, number>>;
    readonly error?: Readonly<{
        readonly code?: string;
        readonly stage?: string;
        readonly resource?: string;
        readonly metric?: string;
    }>;
}
export interface OoxmlResourceMetricsCheckpoint {
    readonly name: string;
    readonly elapsedMs: number;
    readonly usage?: OoxmlResourceUsageSnapshot;
}
export type OoxmlResourceName = ExtensibleLiteral<'archive' | 'archive-entry' | 'xml-event' | 'xml-context' | 'xml-tree' | 'worksheet-row' | 'worksheet-shell'>;
export interface OoxmlResourcePolicySnapshot {
    readonly maxArchiveEntryBytes: number | null;
    readonly maxTotalInflatedBytes: number | null;
    readonly maxArchiveEntries: number | null;
}
export interface OoxmlResourceUsageSnapshot {
    readonly archiveEntryCount: number;
    readonly declaredInflatedBytes: number;
    readonly largestInflatedEntryBytes?: number;
    readonly distinctInflatedBytes: number;
    readonly operationInflatedBytes: number;
}
export interface OoxmlResourceViolation {
    readonly format: OoxmlFormat;
    readonly operation: string;
    readonly resource: OoxmlResourceName;
    readonly metric: OoxmlResourceMetric;
    readonly part?: string;
    readonly limit: number;
    readonly observed: number;
    readonly configurable: boolean;
    readonly usage: OoxmlResourceUsageSnapshot;
}
export function openExternalHyperlink(url: string, allowed?: readonly string[], win?: Pick<Window, 'open'> | undefined): boolean;
export interface OutlinePr {
    summaryBelow: boolean;
    summaryRight: boolean;
}
export interface ParsedWorkbook {
    workbook: Workbook;
    styles: Styles;
    sharedStrings: SharedString[];
}
export type PathCmd = {
    op: 'moveTo';
    x: number;
    y: number;
} | {
    op: 'lineTo';
    x: number;
    y: number;
} | {
    op: 'cubicBezTo';
    x1: number;
    y1: number;
    x2: number;
    y2: number;
    x3: number;
    y3: number;
} | {
    op: 'quadBezTo';
    x1: number;
    y1: number;
    x2: number;
    y2: number;
} | {
    op: 'arcTo';
    wr: number;
    hr: number;
    stAng: number;
    swAng: number;
} | {
    op: 'close';
};
export interface PathInfo {
    w: number;
    h: number;
    commands: PathCmd[];
}
export interface PatternFill {
    fillType: 'pattern';
    fg: string;
    bg: string;
    preset: string;
}
export type PhoneticAlignment = 'left' | 'center' | 'distributed' | 'noControl';
export interface PhoneticProperties {
    fontId: number;
    type?: PhoneticType;
    alignment?: PhoneticAlignment;
}
export interface PhoneticRun {
    sb: number;
    eb: number;
    text: string;
}
export type PhoneticType = 'fullwidthKatakana' | 'halfwidthKatakana' | 'Hiragana' | 'noConversion';
export type PivotCacheSource = {
    kind: 'worksheet';
    sheet?: string;
    reference?: string;
    name?: string;
    relationshipId?: string;
} | {
    kind: 'external';
} | {
    kind: 'consolidation';
} | {
    kind: 'scenario';
};
export interface PivotDataField {
    field: number;
    subtotal?: string;
    rawSubtotal?: string;
    name?: string;
}
export interface PivotDiagnostic {
    part: string;
    reason: {
        kind: 'unreadableWorksheetRelationships';
    } | {
        kind: 'malformedWorksheetRelationships';
    } | {
        kind: 'malformedPivotRelationship';
    } | {
        kind: 'externalPivotRelationship';
    } | {
        kind: 'unreadablePart';
    } | {
        kind: 'malformedXml';
    } | {
        kind: 'missingIdentity';
    } | {
        kind: 'invalidLocation';
    };
}
export interface PivotLocation extends WorksheetCellRange {
    firstHeaderRow: number;
    firstDataRow: number;
    firstDataCol: number;
}
export type PivotMetadataStatus = {
    state: 'complete';
} | {
    state: 'partial';
    reasons: PivotPartialReason[];
};
export interface PivotPageField {
    field: number;
    item?: number;
    name?: string;
}
export type PivotPartialReason = {
    kind: 'missingCacheRelationship';
} | {
    kind: 'malformedCacheRelationships';
} | {
    kind: 'unreadableCacheRelationships';
} | {
    kind: 'externalCacheRelationship';
} | {
    kind: 'ambiguousCacheRelationship';
} | {
    kind: 'unreadableCacheDefinition';
} | {
    kind: 'malformedCacheDefinition';
} | {
    kind: 'malformedField';
    field: string;
} | {
    kind: 'unsupportedCacheSource';
    sourceType: string;
} | {
    kind: 'unresolvedWorksheetSourceRelationship';
} | {
    kind: 'unsupportedSemanticFeature';
    feature: string;
};
export interface PivotTableMetadata {
    name: string;
    cacheId: number;
    location: PivotLocation;
    rowFields: number[];
    columnFields: number[];
    pageFields: PivotPageField[];
    dataFields: PivotDataField[];
    refreshOnLoad?: boolean;
    cacheInvalid?: boolean;
    cacheDefinitionPart?: string;
    cacheSource?: PivotCacheSource;
    status: PivotMetadataStatus;
    extensionUris?: string[];
}
export type RenderViewportToBitmapOptions = Omit<XlsxRenderViewportOptions, 'onTextRun'> & {
    width: number;
    height: number;
};
export type ResolvedList = {
    kind: 'values';
    values: string[];
} | {
    kind: 'formula';
    formula: string;
};
export function resolveSharedStrings(ws: Worksheet, sharedStrings: SharedString[]): Worksheet;
export interface Row {
    index: number;
    height: number | null;
    customHeight?: boolean;
    cells: Cell[];
    outlineLevel?: number;
    collapsed?: boolean;
    hidden?: boolean;
}
export interface Run {
    text: string;
    font?: RunFont;
}
export interface RunFont {
    bold: boolean;
    italic: boolean;
    underline: boolean;
    strike: boolean;
    size?: number;
    color?: string | null;
    name?: string | null;
    underlineStyle?: string;
    vertAlign?: 'superscript' | 'subscript';
}
export interface SecondaryValueAxis {
    min: number | null;
    max: number | null;
    title: string | null;
    hidden: boolean;
    formatCode?: string | null;
    displayUnits?: ChartDisplayUnits | null;
    fontColor?: string | null;
    fontSizeHpt?: number | null;
    fontItalic?: boolean | null;
    fontBold?: boolean | null;
    fontFace?: string | null;
    lineColor?: string | null;
    lineWidthEmu?: number | null;
    lineDash?: string | null;
    lineHidden: boolean;
    majorTickMark: string;
    minorTickMark?: string | null;
    minorGridlines?: boolean;
    minorGridlineColor?: string | null;
    minorGridlineWidthEmu?: number | null;
    minorGridlineDash?: string | null;
    majorGridlines?: boolean;
    majorGridlineColor?: string | null;
    majorGridlineWidthEmu?: number | null;
    majorGridlineDash?: string | null;
    majorUnit?: number | null;
    minorUnit?: number | null;
    logBase?: number | null;
    orientation?: 'minMax' | 'maxMin' | string | null;
    tickLabelPos?: string | null;
    labelAlignment?: 'l' | 'ctr' | 'r' | null;
    labelOffsetPercent?: number | null;
    tickLabelSkip?: number | null;
    tickMarkSkip?: number | null;
    crosses?: string | null;
    crossesAt?: number | null;
    titleFontSizeHpt?: number | null;
    titleFontBold?: boolean | null;
    titleFontItalic?: boolean | null;
    titleFontColor?: string | null;
    titleFontFace?: string | null;
    titleRotation?: number | null;
    titleVerticalMode?: 'horz' | 'vert' | 'vert270' | 'wordArtVert' | 'eaVert' | 'mongolianVert' | 'wordArtVertRtl' | null;
    titleManualLayout?: ChartManualLayout | null;
}
export interface ShapeAnchor {
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    editAs?: string;
    nativeExtCx: number;
    nativeExtCy: number;
    shapes: ShapeInfo[];
}
export type ShapeFill = Exclude<Fill, {
    fillType: 'image';
} | {
    fillType: 'none';
}>;
export type ShapeGeom = {
    type: 'preset';
    name: string;
    adj?: (number | null)[];
} | {
    type: 'custom';
    paths: PathInfo[];
} | {
    type: 'image';
    imagePath: string;
    mimeType: string;
    svgImagePath?: string;
    srcRect?: {
        l: number;
        t: number;
        r: number;
        b: number;
    };
    alpha?: number;
    duotone?: Duotone;
};
export interface ShapeInfo {
    zOrder?: number;
    x: number;
    y: number;
    w: number;
    h: number;
    rot: number;
    flipH?: boolean;
    flipV?: boolean;
    fillColor?: string;
    fill?: ShapeFill;
    strokeColor?: string;
    strokeWidth: number;
    strokeFill?: Exclude<Fill, {
        fillType: 'image';
    } | {
        fillType: 'none';
    }>;
    strokeDashStyle?: string;
    strokeCustomDash?: Array<{
        dash: number;
        space: number;
    }>;
    strokeLineCap?: 'butt' | 'round' | 'square';
    strokeLineJoin?: 'round' | 'bevel' | 'miter';
    strokeMiterLimit?: number;
    strokeAlignment?: 'ctr' | 'in';
    strokeCmpd?: string;
    strokeHeadEnd?: ArrowEnd;
    strokeTailEnd?: ArrowEnd;
    geom: ShapeGeom;
    text?: ShapeText;
}
export interface ShapeParagraph {
    align: string;
    rtl?: boolean;
    marL?: number;
    marR?: number;
    indent?: number;
    spaceLine?: SpaceLine | null;
    runs: ShapeTextRun[];
}
export interface ShapeText {
    anchor: string;
    wrap: string;
    autoFit?: string;
    fontScale?: number | null;
    lnSpcReduction?: number | null;
    lIns: number;
    tIns: number;
    rIns: number;
    bIns: number;
    paragraphs: ShapeParagraph[];
}
export type ShapeTextRun = {
    type: 'text';
    text: string;
    bold: boolean;
    italic: boolean;
    size: number;
    color?: string;
    fontFace?: string;
    fontFaceEa?: string;
    fontFaceCs?: string;
} | {
    type: 'break';
} | {
    type: 'math';
    nodes: MathNode[];
    display: boolean;
    fontSize?: number;
    color?: string;
};
export interface SharedString {
    text: string;
    runs?: Run[];
    phoneticRuns?: PhoneticRun[];
    phoneticPr?: PhoneticProperties;
}
export interface SheetMeta {
    name: string;
    sheetId: number;
    rId: string;
    tabColor?: string | null;
    visibility?: 'hidden' | 'veryHidden';
}
export type SheetVisibility = 'visible' | 'hidden' | 'veryHidden';
export interface SlicerAnchor {
    fromCol: number;
    fromColOff: number;
    fromRow: number;
    fromRowOff: number;
    toCol: number;
    toColOff: number;
    toRow: number;
    toRowOff: number;
    caption: string;
    items: SlicerItem[];
    style?: SlicerStyle;
}
export interface SlicerElementStyle {
    fontColor?: string;
    fontSize?: number;
    fontBold?: boolean;
    fontFamily?: string;
    fillColor?: string;
    borderColor?: string;
}
export interface SlicerItem {
    name: string;
    selected: boolean;
}
export interface SlicerStyle {
    whole?: SlicerElementStyle;
    header?: SlicerElementStyle;
    selectedItemWithData?: SlicerElementStyle;
    unselectedItemWithData?: SlicerElementStyle;
}
export interface SolidFill {
    fillType: 'solid';
    color: string;
}
export type SpaceLine = {
    type: 'pct';
    val: number;
} | {
    type: 'pts';
    val: number;
};
export interface Sparkline {
    row: number;
    col: number;
    values: (number | null)[];
}
export interface SparklineGroup {
    kind: 'line' | 'column' | 'stem';
    markers: boolean;
    high: boolean;
    low: boolean;
    first: boolean;
    last: boolean;
    negative: boolean;
    displayXAxis: boolean;
    displayEmptyCellsAs: string;
    minAxisType: string;
    maxAxisType: string;
    manualMin?: number;
    manualMax?: number;
    lineWeight: number;
    colorSeries?: string;
    colorNegative?: string;
    colorAxis?: string;
    colorMarkers?: string;
    colorFirst?: string;
    colorLast?: string;
    colorHigh?: string;
    colorLow?: string;
    sparklines: Sparkline[];
}
export interface SrcRect {
    l: number;
    t: number;
    r: number;
    b: number;
}
export interface Styles {
    fonts: CellFont[];
    fills: CellFill[];
    borders: Border[];
    cellXfs: CellXf[];
    numFmts: NumFmt[];
    dxfs: Dxf[];
}
export interface TableColumnInfo {
    dataDxfId?: number;
    headerRowDxfId?: number;
    totalsRowDxfId?: number;
}
export interface TableInfo {
    range: WorksheetCellRange;
    styleName: string;
    headerRowCount: number;
    totalsRowCount: number;
    showRowStripes: boolean;
    showColumnStripes: boolean;
    showFirstColumn: boolean;
    showLastColumn: boolean;
    accentColor: string;
    isCustom?: boolean;
    wholeTableDxf?: number;
    headerRowDxf?: number;
    totalRowDxf?: number;
    firstColumnDxf?: number;
    lastColumnDxf?: number;
    band1HorizontalDxf?: number;
    band2HorizontalDxf?: number;
    columns: TableColumnInfo[];
}
export interface TileInfo {
    tx?: number;
    ty?: number;
    sx?: number;
    sy?: number;
    flip?: string;
    algn?: string;
}
export interface ViewerContextMenuEvent<TContext> {
    readonly originalEvent: MouseEvent;
    getContext(): Promise<TContext | null>;
}
export interface ViewportRange {
    row: number;
    col: number;
    rows: number;
    cols: number;
}
export interface Workbook {
    sheets: SheetMeta[];
    date1904?: boolean;
    parseError?: string;
}
export interface Worksheet {
    name: string;
    isChartSheet?: boolean;
    rows: Row[];
    colWidths: Record<number, number>;
    colWidthRanges?: Array<{
        min: number;
        max: number;
        width: number;
    }>;
    colStyleRanges?: Array<{
        min: number;
        max: number;
        styleIndex: number;
    }>;
    rowHeights: Record<number, number>;
    colOutlineLevels?: Record<number, number>;
    colCollapsed?: Record<number, boolean>;
    colHidden?: Record<number, boolean>;
    defaultColWidth: number;
    defaultRowHeight: number;
    defaultRowHeightCustom?: boolean;
    mergeCells: MergeCell[];
    freezeRows: number;
    freezeCols: number;
    conditionalFormats: ConditionalFormat[];
    images: ImageAnchor[];
    charts: ChartAnchor[];
    shapeGroups?: ShapeAnchor[];
    showZeros?: boolean;
    showGridlines?: boolean;
    rightToLeft?: boolean;
    outlinePr?: OutlinePr;
    tabColor?: string | null;
    autoFilter?: WorksheetCellRange | null;
    hyperlinks?: Hyperlink[];
    commentRefs?: string[];
    comments?: XlsxComment[];
    dataValidations?: DataValidation[];
    definedNames?: DefinedName[];
    tables?: TableInfo[];
    slicers?: SlicerAnchor[];
    pivotTables?: PivotTableMetadata[];
    pivotDiagnostics?: PivotDiagnostic[];
    sparklineGroups?: SparklineGroup[];
    defaultFontFamily?: string;
    defaultFontSize?: number;
    date1904?: boolean;
    parseError?: string;
}
export interface WorksheetCellRange {
    top: number;
    left: number;
    bottom: number;
    right: number;
}
export interface XlsxComment {
    cellRef: string;
    author?: string;
    text: string;
}
export type XlsxCopyResult = Readonly<{
    status: 'copied';
    cellCount: number;
    utf16CodeUnits: number;
}> | Readonly<{
    status: 'empty-selection';
}> | Readonly<{
    status: 'unsupported-multiple-areas';
}> | Readonly<{
    status: 'too-large';
    limit: 'cells' | 'text';
}> | Readonly<{
    status: 'clipboard-unavailable';
}> | Readonly<{
    status: 'clipboard-denied';
}>;
export interface XlsxElementAnchorMarker {
    readonly row: number;
    readonly col: number;
    readonly offsetX: number;
    readonly offsetY: number;
}
export interface XlsxElementContext {
    readonly format: 'xlsx';
    readonly kind: 'element';
    readonly sheetIndex: number;
    readonly sheetName: string;
    readonly elementType: 'chart' | 'image' | 'shape';
    readonly elementIndex: number;
    readonly shapeIndex?: number;
    readonly anchor: Readonly<{
        from: XlsxElementAnchorMarker;
        to: XlsxElementAnchorMarker;
    }>;
    readonly text?: string;
    readonly mimeType?: string;
    readonly seriesCount?: number;
    readonly shapeCount?: number;
    readonly truncated: boolean;
    readonly truncationReasons: readonly 'text'[];
    readonly textCharacters: number;
    readonly maxTextCharacters: number;
}
export interface XlsxMatchLocation {
    sheet: number;
    sheetName: string;
    ref: string;
    row: number;
    col: number;
}
export interface XlsxRangeSelectionContext {
    readonly format: 'xlsx';
    readonly kind: 'range';
    readonly sheetIndex: number;
    readonly sheetName: string;
    readonly selection: XlsxSelectionState;
    readonly coordinateCountUpperBound: number;
    readonly cells: readonly XlsxSelectionContextCell[];
    readonly truncated: boolean;
    readonly truncationReasons: readonly ('cells' | 'text')[];
    readonly maxCells: number;
    readonly textCharacters: number;
    readonly maxTextCharacters: number;
}
export interface XlsxRenderViewportOptions {
    width?: number;
    height?: number;
    dpr?: number;
    defaultFontFamily?: string;
    defaultFontSize?: number;
    scrollOffsetX?: number;
    scrollOffsetY?: number;
    freezeRows?: number;
    freezeCols?: number;
    cellScale?: number;
    onTextRun?: (info: XlsxTextRunInfo) => void;
    selectedRowRange?: {
        start: number;
        end: number;
        strong: boolean;
    } | null;
    selectedColRange?: {
        start: number;
        end: number;
        strong: boolean;
    } | null;
}
export interface XlsxScrollToCellOptions {
    readonly align?: 'nearest' | 'start' | 'center' | 'end';
}
export type XlsxSelectionArea = Readonly<{
    kind: 'cells';
    top: number;
    left: number;
    bottom: number;
    right: number;
}> | Readonly<{
    kind: 'rows';
    firstRow: number;
    lastRow: number;
}> | Readonly<{
    kind: 'columns';
    firstColumn: number;
    lastColumn: number;
}> | Readonly<{
    kind: 'sheet';
}>;
export type XlsxSelectionContext = XlsxRangeSelectionContext | XlsxElementContext;
export interface XlsxSelectionContextCell {
    readonly address: CellAddress;
    readonly displayText: string;
    readonly valueType: 'empty' | 'text' | 'number' | 'bool' | 'error' | 'shared';
    readonly value: string | number | boolean | null;
    readonly formula?: string;
}
export interface XlsxSelectionContextOptions {
    readonly maxCells?: number;
    readonly maxTextCharacters?: number;
}
export type XlsxSelectionInput = string | XlsxSelectionState | null;
export interface XlsxSelectionState {
    readonly areas: readonly XlsxSelectionArea[];
    readonly activeAreaIndex: number;
    readonly activeCell: CellAddress;
    readonly extensionAnchor: CellAddress;
}
export class XlsxSheetViewer implements ZoomableViewer {
    readonly canvasElement: HTMLCanvasElement;
    static fromWorkbook(canvasElement: HTMLCanvasElement, workbook: XlsxWorkbook, options?: Omit<XlsxSheetViewerOptions, keyof LoadOptions>): Omit<XlsxSheetViewer, 'load'>;
    constructor(canvasElement: HTMLCanvasElement, options?: XlsxSheetViewerOptions);
    load(source: string | ArrayBuffer): Promise<void>;
    get sheetIndex(): number;
    get sheetCount(): number;
    get sheetNames(): string[];
    goToSheet(index: number): Promise<void>;
    nextSheet(): Promise<void>;
    prevSheet(): Promise<void>;
    getViewportOffset(): XlsxViewportOffset;
    setViewportOffset(offset: XlsxViewportOffset): Promise<void>;
    scrollToCell(ref: string, options?: XlsxScrollToCellOptions): Promise<void>;
    relayout(): Promise<void>;
    getScale(): number;
    setScale(scale: number): void;
    zoomIn(): void;
    zoomOut(): void;
    fitWidth(): void;
    fitPage(): void;
    getCellAt(clientX: number, clientY: number): CellAddress | null;
    get selectionState(): XlsxSelectionState | null;
    setSelection(selection: XlsxSelectionInput): void;
    getSelectionContext(options?: XlsxSelectionContextOptions): XlsxSelectionContext | null;
    copySelection(): Promise<XlsxCopyResult>;
    setSelectionColor(color: string): void;
    setHiddenSheetMode(mode: HiddenSheetMode): Promise<void>;
    get hiddenSheetMode(): HiddenSheetMode;
    get visibleSheetCount(): number;
    findText(query: string, options?: FindMatchesOptions): Promise<FindMatch<XlsxMatchLocation>[]>;
    findNext(): Promise<FindMatch<XlsxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<XlsxMatchLocation> | null>;
    clearFind(): void;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    destroy(): void;
    private __privatePresence;
}
export interface XlsxSheetViewerOptions extends LoadOptions {
    cellScale?: number;
    resizable?: boolean;
    showScrollbars?: boolean;
    zoomMin?: number;
    zoomMax?: number;
    onScaleChange?: (scale: number) => void;
    onReady?: (sheetNames: string[]) => void;
    onSheetChange?: (index: number, total: number) => void;
    onError?: (err: Error) => void;
    onSelectionStateChange?: (selection: XlsxSelectionState | null) => void;
    onSelectionContextChange?: (context: XlsxSelectionContext | null) => void;
    onContextMenu?: (event: ViewerContextMenuEvent<XlsxSelectionContext>) => void;
    enableElementSelection?: boolean;
    onHyperlinkClick?: (target: HyperlinkTarget) => void;
    enableHyperlinks?: boolean;
    selectionColor?: string;
    findHighlightColors?: FindHighlightColors;
    hiddenSheetMode?: HiddenSheetMode;
    onViewportChange?: (offset: XlsxViewportOffset) => void;
}
export interface XlsxTextRunInfo {
    sheetName: string;
    cellRef: string;
    text: string;
    x: number;
    y: number;
    width: number;
    height: number;
    row: number;
    col: number;
}
export class XlsxViewer extends XlsxViewerEngine {
    static fromWorkbook(container: HTMLElement, workbook: XlsxWorkbook, opts?: Omit<XlsxViewerOptions, keyof LoadOptions>): Omit<XlsxViewer, 'load'>;
    constructor(container: HTMLElement, opts?: XlsxViewerOptions);
}
class XlsxViewerEngine implements ZoomableViewer {
    constructor(container: HTMLElement, opts: XlsxViewerOptions | XlsxSheetViewerOptions | undefined, mount: XlsxViewerMount);
    load(source: string | ArrayBuffer): Promise<void>;
    get sheetIndex(): number;
    get sheetCount(): number;
    goToSheet(index: number): Promise<void>;
    nextSheet(): Promise<void>;
    prevSheet(): Promise<void>;
    getViewportOffset(): XlsxViewportOffset;
    setViewportOffset(offset: XlsxViewportOffset): Promise<void>;
    relayout(): Promise<void>;
    scrollToCell(ref: string, options?: XlsxScrollToCellOptions): Promise<void>;
    getCellAt(clientX: number, clientY: number): CellAddress | null;
    get selectionState(): XlsxSelectionState | null;
    setSelection(input: XlsxSelectionInput): void;
    getSelectionContext(options?: XlsxSelectionContextOptions): XlsxSelectionContext | null;
    setSelectionColor(color: string): void;
    setHiddenSheetMode(mode: HiddenSheetMode): Promise<void>;
    get hiddenSheetMode(): HiddenSheetMode;
    get visibleSheetCount(): number;
    copySelection(): Promise<XlsxCopyResult>;
    findText(query: string, opts?: FindMatchesOptions): Promise<FindMatch<XlsxMatchLocation>[]>;
    findNext(): Promise<FindMatch<XlsxMatchLocation> | null>;
    findPrev(): Promise<FindMatch<XlsxMatchLocation> | null>;
    clearFind(): void;
    setScale(scale: number): void;
    getScale(): number;
    zoomIn(): void;
    zoomOut(): void;
    fitWidth(): void;
    fitPage(): void;
    get sheetNames(): string[];
    get canvasElement(): HTMLCanvasElement;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    destroy(): void;
    private __privatePresence;
}
type XlsxViewerMount = {
    readonly kind: 'composite';
} | {
    readonly kind: 'sheet';
    readonly canvas: HTMLCanvasElement;
    readonly mode: CanvasViewerRenderMode;
};
export interface XlsxViewerOptions extends XlsxSheetViewerOptions {
    showZoomSlider?: boolean;
}
export interface XlsxViewportOffset {
    readonly x: number;
    readonly y: number;
}
export class XlsxWorkbook {
    get mode(): 'main' | 'worker';
    static load(source: string | ArrayBuffer, opts?: LoadOptions): Promise<XlsxWorkbook>;
    get sheetNames(): string[];
    get sheetCount(): number;
    get tabColors(): (string | null)[];
    sheetVisibility(sheetIndex: number): SheetVisibility;
    isHidden(sheetIndex: number): boolean;
    getWorksheet(sheetIndex: number): Promise<Worksheet>;
    getResourceMetrics(): Promise<OoxmlResourceMetrics>;
    getImage(imagePath: string, mimeType: string): Promise<Blob>;
    toMarkdown(): Promise<string>;
    resolveValidationList(sheetIndex: number, formula1: string | undefined): Promise<ResolvedList>;
    cellText(ws: Worksheet, cell: Cell): string;
    renderViewport(target: HTMLCanvasElement | OffscreenCanvas, sheetIndex: number, viewport: ViewportRange, opts?: XlsxRenderViewportOptions): Promise<void>;
    renderViewportToBitmap(sheetIndex: number, viewport: ViewportRange, opts: RenderViewportToBitmapOptions): Promise<ImageBitmap>;
    destroy(): void;
    private __privatePresence;
    private constructor();
}
export interface ZoomableViewer {
    getScale(): number;
    setScale(scale: number): void | Promise<void>;
    zoomIn(): void | Promise<void>;
    zoomOut(): void | Promise<void>;
    fitWidth(): void | Promise<void>;
    fitPage(): void | Promise<void>;
}
